### Proyecto Despliegue Soluciones Analiticas

Presentado por:
- Laura Marcela Ramirez Casallas
- Kevin Alejandro Caicedo Rodriguez
- Jhon Jairo Meneses Prieto
- Jeferson Andrés Gutiérrez Gutiérrez

## Pregunta de Negocio


El examen **saber 11°** es una prueba utilizada por el instituto colombiano para la evaluación de la Educación (ICFES)1, para realizar mediciones oficiales acerca de la calidad del servicio educativo prestado a nivel nacional. Esta prueba es practicada a los estudiantes de todos los establecimientos educativos, privados y públicos, que están terminando su formación académica media (grado 11, previo a iniciar la formación universitaria). 

Con este contexto, el problema que vamos a abordar se enfoca en entender cuáles son los factores o variables que inciden en los resultados obtenidos por cada estudiante con el fin de enfocar el uso de los recursos disponibles para implementar políticas públicas que busquen fortalecer las competencias de los estudiantes del país. 

Por tal razón, bajo este contexto, la pregunta de negocio es la siguiente:

#### *¿Cómo puede la secretaria de educacion lograr el aumento de la aprobación del ICFES mediante el análisis de variables demográficas, socioeconómicos e institucionales para identificar brechas de rendimiento y mejorar la calidad educativa de cada una de las instituciones analizadas de la ciudad de Bogotá?*

## Fuente de los datos

Para dar solución al caso de estudio contamos con los datos publicados a través de la plataforma de Datos Abiertos de Colombia, a los que se puede acceder a través del siguiente URL: 

https://www.datos.gov.co/en/Educaci-n/Bogota_historico_saber_11/8qwp-pzhz/about_data

## Importación de Datos

In [1]:
pip install Sodapy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: Sodapy in c:\users\asus admi\appdata\roaming\python\python313\site-packages (2.2.0)
Requirement already satisfied: requests>=2.28.1 in d:\programdata\anaconda3\lib\site-packages (from Sodapy) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\programdata\anaconda3\lib\site-packages (from requests>=2.28.1->Sodapy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\programdata\anaconda3\lib\site-packages (from requests>=2.28.1->Sodapy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\programdata\anaconda3\lib\site-packages (from requests>=2.28.1->Sodapy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\programdata\anaconda3\lib\site-packages (from requests>=2.28.1->Sodapy) (2026.1.4)
Note: you may need to restart the kernel to use updated packages.

Vamos a utilizar el año 2022, que es el mas reciente y el que surge luego de pandemia

In [2]:
from sodapy import Socrata
import pandas as pd

APP_TOKEN = "zkj4BAQIZkr7n4t4NKzvLt5zq"
client = Socrata("datos.gov.co", APP_TOKEN, timeout=120)

dataset_id = "8qwp-pzhz"
periodo_objetivo = 20224

limit = 50000
offset = 0
all_results = []

while True:
    results = client.get(
        dataset_id,
        where=f"periodo = '{periodo_objetivo}'",
        order="estu_consecutivo ASC",
        limit=limit,
        offset=offset
    )

    if not results:
        break

    all_results.extend(results)
    offset += len(results)

    print(f"Descargados {len(all_results)} registros...")

df = pd.DataFrame.from_records(all_results)

print("Total de registros:", len(df))
print("Filas completamente duplicadas:", df.duplicated().sum())
print("Identificadores únicos:", df["estu_consecutivo"].nunique())

Descargados 50000 registros...
Descargados 100000 registros...
Descargados 150000 registros...
Descargados 152584 registros...
Total de registros: 152584
Filas completamente duplicadas: 76331
Identificadores únicos: 76253

In [3]:
print(f"Registros: {df.shape[0]:,}")
print(f"Variables: {df.shape[1]}")
display(df.head())

Registros: 152,584
Variables: 51

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,TI,SB11202240002331,URBANO,N,A,ACADÉMICO,111001014176,111001014176,11,...,Si,Si,Si,A1,56,51,52,46,59,262
1,20224,TI,SB11202240002331,URBANO,N,A,ACADÉMICO,111001014176,111001014176,11,...,Si,Si,Si,A1,56,51,52,46,59,262
2,20224,TI,SB11202240002335,URBANO,N,A,ACADÉMICO,111001014176,111001014176,11,...,No,No,Si,A1,48,51,49,46,45,239
3,20224,TI,SB11202240002335,URBANO,N,A,ACADÉMICO,111001014176,111001014176,11,...,No,No,Si,A1,48,51,49,46,45,239
4,20224,TI,SB11202240002340,URBANO,N,A,ACADÉMICO,111001076376,111001076376,11,...,No,No,Si,A-,42,45,34,39,55,216

In [4]:
display(df.info())
display(df.describe(include="all").T)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152584 entries, 0 to 152583
Data columns (total 51 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   periodo                        152584 non-null  object
 1   estu_tipodocumento             152584 non-null  object
 2   estu_consecutivo               152584 non-null  object
 3   cole_area_ubicacion            152584 non-null  object
 4   cole_bilingue                  124416 non-null  object
 5   cole_calendario                152584 non-null  object
 6   cole_caracter                  145548 non-null  object
 7   cole_cod_dane_establecimiento  152584 non-null  object
 8   cole_cod_dane_sede             152584 non-null  object
 9   cole_cod_depto_ubicacion       152584 non-null  object
 10  cole_cod_mcpio_ubicacion       152584 non-null  object
 11  cole_codigo_icfes              152584 non-null  object
 12  cole_depto_ubicacion           152584 non-null  object
 13  cole_genero                    152584 non-null  object
 14  cole_jornada                   152584 non-null  object
 15  cole_mcpio_ubicacion           152584 non-null  object
 16  cole_naturaleza                152584 non-null  object
 17  cole_nombre_establecimiento    152584 non-null  object
 18  cole_nombre_sede               152584 non-null  object
 19  cole_sede_principal            152584 non-null  object
 20  estu_cod_depto_presentacion    152584 non-null  object
 21  estu_cod_mcpio_presentacion    152584 non-null  object
 22  estu_cod_reside_depto          152584 non-null  object
 23  estu_cod_reside_mcpio          152584 non-null  object
 24  estu_depto_presentacion        152584 non-null  object
 25  estu_depto_reside              152584 non-null  object
 26  estu_estadoinvestigacion       152584 non-null  object
 27  estu_estudiante                152584 non-null  object
 28  estu_fechanacimiento           152584 non-null  object
 29  estu_genero                    152584 non-null  object
 30  estu_mcpio_presentacion        152584 non-null  object
 31  estu_mcpio_reside              152584 non-null  object
 32  estu_nacionalidad              152584 non-null  object
 33  estu_pais_reside               152584 non-null  object
 34  estu_privado_libertad          152584 non-null  object
 35  fami_cuartoshogar              148254 non-null  object
 36  fami_educacionmadre            146496 non-null  object
 37  fami_educacionpadre            146476 non-null  object
 38  fami_estratovivienda           146070 non-null  object
 39  fami_personashogar             148460 non-null  object
 40  fami_tieneautomovil            148238 non-null  object
 41  fami_tienecomputador           148454 non-null  object
 42  fami_tieneinternet             146384 non-null  object
 43  fami_tienelavadora             148402 non-null  object
 44  desemp_ingles                  152554 non-null  object
 45  punt_ingles                    152554 non-null  object
 46  punt_matematicas               152584 non-null  object
 47  punt_sociales_ciudadanas       152584 non-null  object
 48  punt_c_naturales               152584 non-null  object
 49  punt_lectura_critica           152584 non-null  object
 50  punt_global                    152584 non-null  object
dtypes: object(51)
memory usage: 59.4+ MB

None

,count,unique,top,freq
periodo,152584,1,20224,152584
estu_tipodocumento,152584,11,TI,131232
estu_consecutivo,152584,76253,SB11202240071815,4
cole_area_ubicacion,152584,2,URBANO,151258
cole_bilingue,124416,2,N,123762
cole_calendario,152584,3,A,151360
cole_caracter,145548,4,ACADÉMICO,124824
cole_cod_dane_establecimiento,152584,1131,111001024732,852
cole_cod_dane_sede,152584,1143,111001024732,852
cole_cod_depto_ubicacion,152584,1,11,152584
cole_cod_mcpio_ubicacion,152584,1,11001,152584
cole_codigo_icfes,152584,1460,740506,736
cole_depto_ubicacion,152584,1,BOGOTÁ,152584
cole_genero,152584,3,MIXTO,144332
cole_jornada,152584,6,COMPLETA,47434
cole_mcpio_ubicacion,152584,1,BOGOTÁ D.C.,152584
cole_naturaleza,152584,2,OFICIAL,87896
cole_nombre_establecimiento,152584,1111,COLEGIO TECNISISTEMAS,1340
cole_nombre_sede,152584,1125,COLEGIO TECNISISTEMAS - SEDE PRINCIPAL,1010
cole_sede_principal,152584,2,S,147866
estu_cod_depto_presentacion,152584,31,11,149766
estu_cod_mcpio_presentacion,152584,171,11001,149766
estu_cod_reside_depto,152584,30,11,149784
estu_cod_reside_mcpio,152584,206,11001,149784
estu_depto_presentacion,152584,31,BOGOTÁ,149766
estu_depto_reside,152584,30,BOGOTÁ,149784
estu_estadoinvestigacion,152584,2,PUBLICAR,152536
estu_estudiante,152584,1,ESTUDIANTE,152584
estu_fechanacimiento,152584,3692,05/10/2005,318
estu_genero,152584,2,F,79844
estu_mcpio_presentacion,152584,170,BOGOTÁ D.C.,149766
estu_mcpio_reside,152584,205,BOGOTÁ D.C.,149784
estu_nacionalidad,152584,24,COLOMBIA,150322
estu_pais_reside,152584,24,COLOMBIA,150322
estu_privado_libertad,152584,2,N,152504
fami_cuartoshogar,148254,6,Tres,63912
fami_educacionmadre,146496,12,Secundaria (Bachillerato) completa,42430
fami_educacionpadre,146476,12,Secundaria (Bachillerato) completa,40308
fami_estratovivienda,146070,7,Estrato 2,62920
fami_personashogar,148460,5,3 a 4,83860
fami_tieneautomovil,148238,2,No,93328
fami_tienecomputador,148454,2,Si,117884
fami_tieneinternet,146384,2,Si,135816
fami_tienelavadora,148402,2,Si,135272
desemp_ingles,152554,5,A1,44752
punt_ingles,152554,60,56,4976
punt_matematicas,152584,72,54,5506
punt_sociales_ciudadanas,152584,71,55,4956
punt_c_naturales,152584,61,51,5696
punt_lectura_critica,152584,62,59,6110
punt_global,152584,315,277,1410

# Diagnósitico de calidad de datos

### Nulos x columnas

In [5]:
resumen_nulos = pd.DataFrame({
    "nulos": df.isna().sum(),
    "porcentaje_nulos": (df.isna().mean() * 100).round(2)
})

resumen_nulos = resumen_nulos.query("nulos > 0")
resumen_nulos = resumen_nulos.sort_values(
    "porcentaje_nulos",
    ascending=False
)

display(resumen_nulos)

                      nulos  porcentaje_nulos
cole_bilingue         28168             18.46
cole_caracter          7036              4.61
fami_estratovivienda   6514              4.27
fami_tieneinternet     6200              4.06
fami_educacionpadre    6108              4.00
fami_educacionmadre    6088              3.99
fami_tieneautomovil    4346              2.85
fami_cuartoshogar      4330              2.84
fami_tienelavadora     4182              2.74
fami_tienecomputador   4130              2.71
fami_personashogar     4124              2.70
desemp_ingles            30              0.02
punt_ingles              30              0.02

### Duplicidad

In [6]:
print('Filas duplicadas: ', df.duplicated().sum())
print("Duplicados por estudiante:",df["estu_consecutivo"].duplicated().sum())

Filas duplicadas:  76331
Duplicados por estudiante: 76331

In [7]:
# ver estudiantes que mas se repiten
df["estu_consecutivo"].value_counts().loc[lambda x: x > 1]

estu_consecutivo
SB11202240071815    4
SB11202240072159    4
SB11202240072128    4
SB11202240072129    4
SB11202240072133    4
                   ..
SB11202240169128    2
SB11202240169119    2
SB11202240169113    2
SB11202240169112    2
SB11202240616361    2
Name: count, Length: 76253, dtype: int64

In [8]:
pd.set_option('display.max_columns', None)

df_duplicados = df[
    df.duplicated(keep=False)
]

display(df_duplicados[df_duplicados['estu_consecutivo']=='SB11202240072129'])

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,cole_cod_mcpio_ubicacion,cole_codigo_icfes,cole_depto_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,cole_nombre_establecimiento,cole_nombre_sede,cole_sede_principal,estu_cod_depto_presentacion,estu_cod_mcpio_presentacion,estu_cod_reside_depto,estu_cod_reside_mcpio,estu_depto_presentacion,estu_depto_reside,estu_estadoinvestigacion,estu_estudiante,estu_fechanacimiento,estu_genero,estu_mcpio_presentacion,estu_mcpio_reside,estu_nacionalidad,estu_pais_reside,estu_privado_libertad,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
21912,20224,TI,SB11202240072129,URBANO,N,A,ACADÉMICO,111001000612,111001000612,11,11001,023382,BOGOTÁ,FEMENINO,TARDE,BOGOTÁ D.C.,OFICIAL,COLEGIO FEMENINO LORENCITA VILLEGAS DE SANTOS ...,SEDE A,S,11,11001,11,11001,BOGOTÁ,BOGOTÁ,PUBLICAR,ESTUDIANTE,23/08/2004,F,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,COLOMBIA,N,Dos,Educación profesional completa,Secundaria (Bachillerato) incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,A2,64,55,64,66,69,318
21913,20224,TI,SB11202240072129,URBANO,N,A,ACADÉMICO,111001000612,111001000612,11,11001,023382,BOGOTÁ,FEMENINO,TARDE,BOGOTÁ D.C.,OFICIAL,COLEGIO FEMENINO LORENCITA VILLEGAS DE SANTOS ...,SEDE A,S,11,11001,11,11001,BOGOTÁ,BOGOTÁ,PUBLICAR,ESTUDIANTE,23/08/2004,F,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,COLOMBIA,N,Dos,Educación profesional completa,Secundaria (Bachillerato) incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,A2,64,55,64,66,69,318
21914,20224,TI,SB11202240072129,URBANO,N,A,ACADÉMICO,111001000612,111001000612,11,11001,023382,BOGOTÁ,FEMENINO,TARDE,BOGOTÁ D.C.,OFICIAL,COLEGIO FEMENINO LORENCITA VILLEGAS DE SANTOS ...,SEDE A,S,11,11001,11,11001,BOGOTÁ,BOGOTÁ,PUBLICAR,ESTUDIANTE,23/08/2004,F,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,COLOMBIA,N,Dos,Educación profesional completa,Secundaria (Bachillerato) incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,A2,64,55,64,66,69,318
21915,20224,TI,SB11202240072129,URBANO,N,A,ACADÉMICO,111001000612,111001000612,11,11001,023382,BOGOTÁ,FEMENINO,TARDE,BOGOTÁ D.C.,OFICIAL,COLEGIO FEMENINO LORENCITA VILLEGAS DE SANTOS ...,SEDE A,S,11,11001,11,11001,BOGOTÁ,BOGOTÁ,PUBLICAR,ESTUDIANTE,23/08/2004,F,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,COLOMBIA,N,Dos,Educación profesional completa,Secundaria (Bachillerato) incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,A2,64,55,64,66,69,318

Se confirma que la duplicidad es en todos los campos

### Tipos de Datos

In [9]:
for columna in df.columns:
    print(f"{columna}: {df[columna].dtype}")

periodo: object
estu_tipodocumento: object
estu_consecutivo: object
cole_area_ubicacion: object
cole_bilingue: object
cole_calendario: object
cole_caracter: object
cole_cod_dane_establecimiento: object
cole_cod_dane_sede: object
cole_cod_depto_ubicacion: object
cole_cod_mcpio_ubicacion: object
cole_codigo_icfes: object
cole_depto_ubicacion: object
cole_genero: object
cole_jornada: object
cole_mcpio_ubicacion: object
cole_naturaleza: object
cole_nombre_establecimiento: object
cole_nombre_sede: object
cole_sede_principal: object
estu_cod_depto_presentacion: object
estu_cod_mcpio_presentacion: object
estu_cod_reside_depto: object
estu_cod_reside_mcpio: object
estu_depto_presentacion: object
estu_depto_reside: object
estu_estadoinvestigacion: object
estu_estudiante: object
estu_fechanacimiento: object
estu_genero: object
estu_mcpio_presentacion: object
estu_mcpio_reside: object
estu_nacionalidad: object
estu_pais_reside: object
estu_privado_libertad: object
fami_cuartoshogar: object
fami_educacionmadre: object
fami_educacionpadre: object
fami_estratovivienda: object
fami_personashogar: object
fami_tieneautomovil: object
fami_tienecomputador: object
fami_tieneinternet: object
fami_tienelavadora: object
desemp_ingles: object
punt_ingles: object
punt_matematicas: object
punt_sociales_ciudadanas: object
punt_c_naturales: object
punt_lectura_critica: object
punt_global: object

Todas las columnas aparecen como object. Esto puede ocurrir porque los datos se descargaron desde Socrata como texto.

### Categorias unicas x cvariable

In [10]:
for col in df.columns:
    print(f'Columna: {col} , Valores Unicos: {df[col].unique()}')

Columna: periodo , Valores Unicos: ['20224']
Columna: estu_tipodocumento , Valores Unicos: ['TI' 'CC' 'CR' 'CE' 'PEP' 'NES' 'PPT' 'NUIP' 'RC' 'PE' 'PC']
Columna: estu_consecutivo , Valores Unicos: ['SB11202240002331' 'SB11202240002335' 'SB11202240002340' ...
 'SB11202240616309' 'SB11202240616360' 'SB11202240616361']
Columna: cole_area_ubicacion , Valores Unicos: ['URBANO' 'RURAL']
Columna: cole_bilingue , Valores Unicos: ['N' nan 'S']
Columna: cole_calendario , Valores Unicos: ['A' 'OTRO' 'B']
Columna: cole_caracter , Valores Unicos: ['ACADÉMICO' 'TÉCNICO/ACADÉMICO' nan 'TÉCNICO' 'NO APLICA']
Columna: cole_cod_dane_establecimiento , Valores Unicos: ['111001014176' '111001076376' '111001035572' ... '311001043159'
 '311001096783' '311001003271']
Columna: cole_cod_dane_sede , Valores Unicos: ['111001014176' '111001076376' '111001035572' ... '311001043159'
 '311001096783' '311001003271']
Columna: cole_cod_depto_ubicacion , Valores Unicos: ['11']
Columna: cole_cod_mcpio_ubicacion , Valores Unicos: ['11001']
Columna: cole_codigo_icfes , Valores Unicos: ['736918' '098772' '139956' ... '730291' '166686' '021196']
Columna: cole_depto_ubicacion , Valores Unicos: ['BOGOTÁ']
Columna: cole_genero , Valores Unicos: ['MIXTO' 'MASCULINO' 'FEMENINO']
Columna: cole_jornada , Valores Unicos: ['UNICA' 'TARDE' 'MAÑANA' 'NOCHE' 'COMPLETA' 'SABATINA']
Columna: cole_mcpio_ubicacion , Valores Unicos: ['BOGOTÁ D.C.']
Columna: cole_naturaleza , Valores Unicos: ['OFICIAL' 'NO OFICIAL']
Columna: cole_nombre_establecimiento , Valores Unicos: ['COLEGIO SAN CRISTOBAL SUR (IED)' 'COLEGIO MARRUECOS Y MOLINOS (IED)'
 'COLEGIO ACACIA II (IED)' ... 'COLEGIO EMMANUEL' 'COLEGIO MOUNT VERNON'
 'COLEGIO EUCARISTICO']
Columna: cole_nombre_sede , Valores Unicos: ['CENT EDUC DIST SAN CRISTOBAL SUR' 'CENT EDUC DIST MARRUECOS Y MOLINOS'
 'CENT EDUC DIST ACACIA II' ... 'COLEGIO EMMANUEL' 'COLEGIO MOUNT VERNON'
 'COLEGIO EUCARISTICO']
Columna: cole_sede_principal , Valores Unicos: ['S' 'N']
Columna: estu_cod_depto_presentacion , Valores Unicos: ['11' '25' '19' '68' '73' '95' '23' '13' '18' '70' '66' '41' '15' '47'
 '63' '08' '50' '05' '76' '88' '17' '86' '20' '54' '85' '52' '99' '44'
 '81' '27' '91']
Columna: estu_cod_mcpio_presentacion , Valores Unicos: ['11001' '25843' '25754' '25175' '19001' '25126' '25473' '68615' '73349'
 '95001' '25899' '25513' '25402' '73236' '25040' '73001' '23001' '25377'
 '25430' '25875' '25148' '13001' '18001' '19743' '70215' '66440' '13052'
 '73555' '25297' '68081' '41551' '66001' '15531' '47001' '41359' '63001'
 '08001' '68276' '41001' '50001' '25394' '05001' '76001' '41298' '25286'
 '25269' '05266' '88001' '17013' '25386' '15759' '15238' '05088' '76520'
 '66088' '41396' '41524' '05847' '68547' '50006' '05887' '68001' '86568'
 '20001' '68077' '54720' '05360' '08758' '15001' '50573' '25307' '54001'
 '25740' '47245' '05579' '05376' '85001' '76892' '05615' '05318' '15599'
 '05031' '17380' '25290' '76130' '66170' '05308' '68689' '17614' '17001'
 '08433' '25183' '52001' '99001' '15861' '25279' '44650' '25035' '15572'
 '44430' '54518' '68190' '18150' '63130' '15176' '19418' '86320' '15693'
 '15757' '15516' '85139' '17174' '17541' '73268' '73585' '73352' '15299'
 '73449' '17042' '15667' '81794' '25151' '44847' '52683' '73148' '47318'
 '41306' '85250' '05148' '25245' '54498' '88564' '08638' '54405' '76364'
 '18247' '50568' '27001' '13667' '05310' '70708' '05042' '05664' '05631'
 '66400' '68444' '73408' '13670' '05736' '08634' '91001' '73168' '68235'
 '25769' '68307' '19698' '05761' '05212' '05380' '52399' '68755' '15469'
 '23466' '86001' '50606' '05440' '73411' '25320' '81001' '15837' '25815']
Columna: estu_cod_reside_depto , Valores Unicos: ['11' '25' '52' '73' '17' '23' '41' '13' '18' '70' '66' '08' '68' '97'
 '15' '63' '05' '76' '88' '19' '50' '86' '20' '54' '47' '85' '99' '44'
 '27' '81']
Columna: estu_cod_reside_mcpio , Valores Unicos: ['11001' '25754' '25175' '25214' '25817' '25286' '25473' '25001' '25126'
 '25785' '52480' '73449' '25841' '17001' '23001' '25430' '25513' '25402'
 '25040' '25645' '73055' '25322' '25377' '41206' '25295' '25875' '25148'
 '13001' '18001' '70230' '66440' '08433' '25758' '73275' '73555' '73001'
 '25297' '68081' '25899' '97001' '15531' '63001' '08001' '68276' '41001'
 '25658' '41078' '05001' '76001' '41298' '25269' '05266' '88001' '17013'
 '25426' '15759' '15238' '05088' '05282' '66001' '76520' '66456' '41396'
 '41357' '05847' '19001' '68547' '50006' '05887' '68001' '86568' '20001'
 '50001' '68077' '54720' '25120' '05360' '08758' '25530' '50573' '25307'
 '15001' '54001' '25506' '25740' '25662' '47001' '05579' '05376' '85001'
 '76892' '52835' '15500' '05615' '05318' '15104' '05031' '17380' '15367'
 '25290' '76130' '66170' '68689' '41791' '25200' '25873' '52001' '99001'
 '15861' '25743' '25181' '25279' '41006' '25035' '15572' '25260' '44430'
 '05308' '54518' '68190' '63130' '15176' '15362' '19418' '25372' '86320'
 '15693' '68377' '05197' '15757' '73148' '15516' '85139' '17174' '17495'
 '17433' '73268' '73563' '73226' '15299' '17042' '15667' '25736' '25183'
 '25486' '05697' '25151' '44847' '73873' '15761' '15763' '25168' '47318'
 '25099' '41306' '85430' '85250' '05400' '05148' '25245' '54498' '88564'
 '17873' '08638' '54405' '76364' '18247' '50568' '27001' '05315' '70708'
 '05042' '25898' '05664' '05631' '66400' '73408' '05736' '05607' '08634'
 '73349' '25769' '73770' '19698' '05761' '05212' '05380' '25799' '25178'
 '52399' '25843' '68522' '15816' '25612' '52258' '23466' '50606' '05440'
 '25599' '73411' '50124' '20013' '25772' '25320' '81001' '25815']
Columna: estu_depto_presentacion , Valores Unicos: ['BOGOTÁ' 'CUNDINAMARCA' 'CAUCA' 'SANTANDER' 'TOLIMA' 'GUAVIARE' 'CORDOBA'
 'BOLIVAR' 'CAQUETA' 'SUCRE' 'RISARALDA' 'HUILA' 'BOYACA' 'MAGDALENA'
 'QUINDIO' 'ATLANTICO' 'META' 'ANTIOQUIA' 'VALLE' 'SAN ANDRES' 'CALDAS'
 'PUTUMAYO' 'CESAR' 'NORTE SANTANDER' 'CASANARE' 'NARIÑO' 'VICHADA'
 'LA GUAJIRA' 'ARAUCA' 'CHOCO' 'AMAZONAS']
Columna: estu_depto_reside , Valores Unicos: ['BOGOTÁ' 'CUNDINAMARCA' 'NARIÑO' 'TOLIMA' 'CALDAS' 'CORDOBA' 'HUILA'
 'BOLIVAR' 'CAQUETA' 'SUCRE' 'RISARALDA' 'ATLANTICO' 'SANTANDER' 'VAUPES'
 'BOYACA' 'QUINDIO' 'ANTIOQUIA' 'VALLE' 'SAN ANDRES' 'CAUCA' 'META'
 'PUTUMAYO' 'CESAR' 'NORTE SANTANDER' 'MAGDALENA' 'CASANARE' 'VICHADA'
 'LA GUAJIRA' 'CHOCO' 'ARAUCA']
Columna: estu_estadoinvestigacion , Valores Unicos: ['PUBLICAR' 'VALIDEZ OFICINA JURÍDICA']
Columna: estu_estudiante , Valores Unicos: ['ESTUDIANTE']
Columna: estu_fechanacimiento , Valores Unicos: ['19/07/2004' '10/01/2004' '22/08/2004' ... '04/03/1992' '08/09/2007'
 '15/01/2055']
Columna: estu_genero , Valores Unicos: ['F' 'M']
Columna: estu_mcpio_presentacion , Valores Unicos: ['BOGOTÁ D.C.' 'VILLA DE SAN DIEGO DE UBATÉ' 'SOACHA' 'CHÍA' 'POPAYÁN'
 'CAJICÁ' 'MOSQUERA' 'RIONEGRO' 'HONDA' 'SAN JOSÉ DEL GUAVIARE'
 'ZIPAQUIRÁ' 'PACHO' 'LA VEGA' 'DOLORES' 'ANOLAIMA' 'IBAGUÉ' 'MONTERÍA'
 'LA CALERA' 'MADRID' 'VILLETA' 'CAPARRAPÍ' 'CARTAGENA DE INDIAS'
 'FLORENCIA' 'SILVIA' 'COROZAL' 'MARSELLA' 'ARJONA' 'PLANADAS' 'GACHETÁ'
 'BARRANCABERMEJA' 'PITALITO' 'PEREIRA' 'PAUNA' 'SANTA MARTA' 'ISNOS'
 'ARMENIA' 'BARRANQUILLA' 'FLORIDABLANCA' 'NEIVA' 'VILLAVICENCIO'
 'LA PALMA' 'MEDELLÍN' 'CALI' 'GARZÓN' 'FUNZA' 'FACATATIVÁ' 'ENVIGADO'
 'SAN ANDRÉS' 'AGUADAS' 'LA MESA' 'SOGAMOSO' 'DUITAMA' 'BELLO' 'PALMIRA'
 'BELÉN DE UMBRÍA' 'LA PLATA' 'PALERMO' 'URRAO' 'PIEDECUESTA' 'ACACÍAS'
 'YARUMAL' 'BUCARAMANGA' 'PUERTO ASÍS' 'VALLEDUPAR' 'BARBOSA' 'SARDINATA'
 'ITAGÜÍ' 'SOLEDAD' 'TUNJA' 'PUERTO LÓPEZ' 'GIRARDOT' 'CÚCUTA' 'SIBATÉ'
 'EL BANCO' 'PUERTO BERRÍO' 'LA CEJA' 'YOPAL' 'YUMBO' 'GUARNE' 'RAMIRIQUÍ'
 'AMALFI' 'LA DORADA' 'FUSAGASUGÁ' 'CANDELARIA' 'DOSQUEBRADAS' 'GIRARDOTA'
 'SAN VICENTE DE CHUCURÍ' 'RIOSUCIO' 'MANIZALES' 'MALAMBO' 'CHOCONTÁ'
 'PASTO' 'PUERTO CARREÑO' 'VENTAQUEMADA' 'FÓMEQUE' 'SAN JUAN DEL CESAR'
 'ANAPOIMA' 'PUERTO BOYACÁ' 'MAICAO' 'PAMPLONA' 'CIMITARRA'
 'CARTAGENA DEL CHAIRÁ' 'CALARCÁ' 'CHIQUINQUIRÁ' 'LÓPEZ DE MICAY' 'ORITO'
 'SANTA ROSA DE VITERBO' 'SOCHA' 'PAIPA' 'MANÍ' 'CHINCHINÁ' 'PENSILVANIA'
 'ESPINAL' 'PURIFICACIÓN' 'ICONONZO' 'GARAGOA' 'MELGAR' 'ANSERMA'
 'SAN LUIS DE GACENO' 'TAME' 'CÁQUEZA' 'URIBIA' 'SANDONÁ'
 'CARMEN DE APICALÁ' 'GUAMAL' 'GIGANTE' 'PAZ DE ARIPORO'
 'EL CARMEN DE VIBORAL' 'EL COLEGIO' 'OCAÑA' 'PROVIDENCIA' 'SABANALARGA'
 'LOS PATIOS' 'JAMUNDÍ' 'EL DONCELLO' 'PUERTO GAITÁN' 'QUIBDÓ'
 'SAN MARTÍN DE LOBA' 'GÓMEZ PLATA' 'SAN MARCOS' 'SANTA FÉ DE ANTIOQUIA'
 'SAN PEDRO DE LOS MILAGROS' 'SABANETA' 'LA VIRGINIA' 'MATANZA' 'LÉRIDA'
 'SAN PABLO' 'SEGOVIA' 'SABANAGRANDE' 'LETICIA' 'CHAPARRAL'
 'EL CARMEN DE CHUCURÍ' 'SUBACHOQUE' 'GIRÓN' 'SANTANDER DE QUILICHAO'
 'SOPETRÁN' 'COPACABANA' 'LA ESTRELLA' 'LA UNIÓN' 'SOCORRO' 'MONIQUIRÁ'
 'MONTELÍBANO' 'MOCOA' 'RESTREPO' 'MARINILLA' 'LÍBANO' 'GUADUAS' 'ARAUCA'
 'TUTA' 'TOCAIMA']
Columna: estu_mcpio_reside , Valores Unicos: ['BOGOTÁ D.C.' 'SOACHA' 'CHÍA' 'COTA' 'TOCANCIPÁ' 'FUNZA' 'MOSQUERA'
 'AGUA DE DIOS' 'CAJICÁ' 'TABIO' 'NARIÑO' 'MELGAR' 'UBAQUE' 'MANIZALES'
 'MONTERÍA' 'MADRID' 'PACHO' 'LA VEGA' 'ANOLAIMA'
 'SAN ANTONIO DEL TEQUENDAMA' 'ARMERO' 'GUASCA' 'LA CALERA' 'COLOMBIA'
 'GACHANCIPÁ' 'VILLETA' 'CAPARRAPÍ' 'CARTAGENA DE INDIAS' 'FLORENCIA'
 'CHALÁN' 'MARSELLA' 'MALAMBO' 'SOPÓ' 'FLANDES' 'PLANADAS' 'IBAGUÉ'
 'GACHETÁ' 'BARRANCABERMEJA' 'ZIPAQUIRÁ' 'MITÚ' 'PAUNA' 'ARMENIA'
 'BARRANQUILLA' 'FLORIDABLANCA' 'NEIVA' 'SAN FRANCISCO' 'BARAYA'
 'MEDELLÍN' 'CALI' 'GARZÓN' 'FACATATIVÁ' 'ENVIGADO' 'SAN ANDRÉS' 'AGUADAS'
 'MACHETÁ' 'SOGAMOSO' 'DUITAMA' 'BELLO' 'FREDONIA' 'PEREIRA' 'PALMIRA'
 'MISTRATÓ' 'LA PLATA' 'ÍQUIRA' 'URRAO' 'POPAYÁN' 'PIEDECUESTA' 'ACACÍAS'
 'YARUMAL' 'BUCARAMANGA' 'PUERTO ASÍS' 'VALLEDUPAR' 'VILLAVICENCIO'
 'BARBOSA' 'SARDINATA' 'CABRERA' 'ITAGÜÍ' 'SOLEDAD' 'PARATEBUENO'
 'PUERTO LÓPEZ' 'GIRARDOT' 'TUNJA' 'CÚCUTA' 'VENECIA' 'SIBATÉ'
 'SAN JUAN DE RIOSECO' 'SANTA MARTA' 'PUERTO BERRÍO' 'LA CEJA' 'YOPAL'
 'YUMBO' 'SAN ANDRÉS DE TUMACO' 'OICATÁ' 'RIONEGRO' 'GUARNE' 'BOYACÁ'
 'AMALFI' 'LA DORADA' 'JENESANO' 'FUSAGASUGÁ' 'CANDELARIA' 'DOSQUEBRADAS'
 'SAN VICENTE DE CHUCURÍ' 'TARQUI' 'COGUA' 'VILLAPINZÓN' 'PASTO'
 'PUERTO CARREÑO' 'VENTAQUEMADA' 'SILVANIA' 'CHOACHÍ' 'FÓMEQUE' 'ACEVEDO'
 'ANAPOIMA' 'PUERTO BOYACÁ' 'EL ROSAL' 'MAICAO' 'GIRARDOTA' 'PAMPLONA'
 'CIMITARRA' 'CALARCÁ' 'CHIQUINQUIRÁ' 'IZA' 'LÓPEZ DE MICAY' 'JUNÍN'
 'ORITO' 'SANTA ROSA DE VITERBO' 'LA BELLEZA' 'COCORNÁ' 'SOCHA'
 'CARMEN DE APICALÁ' 'PAIPA' 'MANÍ' 'CHINCHINÁ' 'NORCASIA' 'MANZANARES'
 'ESPINAL' 'PRADO' 'CUNDAY' 'GARAGOA' 'ANSERMA' 'SAN LUIS DE GACENO'
 'SESQUILÉ' 'CHOCONTÁ' 'NEMOCÓN' 'EL SANTUARIO' 'CÁQUEZA' 'URIBIA'
 'VILLARRICA' 'SOMONDOCO' 'SOTAQUIRÁ' 'CHAGUANÍ' 'GUAMAL' 'BOJACÁ'
 'GIGANTE' 'TRINIDAD' 'PAZ DE ARIPORO' 'LA UNIÓN' 'EL CARMEN DE VIBORAL'
 'EL COLEGIO' 'OCAÑA' 'PROVIDENCIA' 'VILLAMARÍA' 'SABANALARGA'
 'LOS PATIOS' 'JAMUNDÍ' 'EL DONCELLO' 'PUERTO GAITÁN' 'QUIBDÓ' 'GUADALUPE'
 'SAN MARCOS' 'SANTA FÉ DE ANTIOQUIA' 'ZIPACÓN'
 'SAN PEDRO DE LOS MILAGROS' 'SABANETA' 'LA VIRGINIA' 'LÉRIDA' 'SEGOVIA'
 'RETIRO' 'SABANAGRANDE' 'HONDA' 'SUBACHOQUE' 'SUÁREZ'
 'SANTANDER DE QUILICHAO' 'SOPETRÁN' 'COPACABANA' 'LA ESTRELLA' 'TENJO'
 'CHIPAQUE' 'VILLA DE SAN DIEGO DE UBATÉ' 'PALMAR' 'TOGÜÍ' 'RICAURTE'
 'EL TABLÓN DE GÓMEZ' 'MONTELÍBANO' 'RESTREPO' 'MARINILLA' 'APULO'
 'LÍBANO' 'CABUYARO' 'AGUSTÍN CODAZZI' 'SUESCA' 'GUADUAS' 'ARAUCA'
 'TOCAIMA']
Columna: estu_nacionalidad , Valores Unicos: ['COLOMBIA' 'VENEZUELA' 'REPÚBLICA DOMINICANA' 'CHILE' 'ECUADOR'
 'ESTADOS UNIDOS' 'ARGENTINA' 'EL SALVADOR' 'GUATEMALA' 'ITALIA' 'ESPAÑA'
 'PERÚ' 'CUBA' 'VANUATU' 'CABO VERDE' 'BRASIL' 'PORTUGAL' 'MÉXICO'
 'COREA DEL SUR' 'URUGUAY' 'COSTA RICA' 'PANAMÁ' 'ALEMANIA' 'TURQUÍA']
Columna: estu_pais_reside , Valores Unicos: ['COLOMBIA' 'VENEZUELA' 'REPÚBLICA DOMINICANA' 'CHILE' 'ECUADOR'
 'ESTADOS UNIDOS' 'ARGENTINA' 'EL SALVADOR' 'GUATEMALA' 'ITALIA' 'ESPAÑA'
 'PERÚ' 'CUBA' 'VANUATU' 'CABO VERDE' 'BRASIL' 'PORTUGAL' 'MÉXICO'
 'COREA DEL SUR' 'URUGUAY' 'COSTA RICA' 'PANAMÁ' 'ALEMANIA' 'TURQUÍA']
Columna: estu_privado_libertad , Valores Unicos: ['N' 'S']
Columna: fami_cuartoshogar , Valores Unicos: ['Tres' 'Dos' 'Cuatro' 'Seis o mas' nan 'Cinco' 'Uno']
Columna: fami_educacionmadre , Valores Unicos: ['Secundaria (Bachillerato) incompleta'
 'Secundaria (Bachillerato) completa' 'Primaria completa'
 'Técnica o tecnológica completa' 'Educación profesional completa'
 'Educación profesional incompleta' 'Primaria incompleta'
 'Técnica o tecnológica incompleta' nan 'No sabe' 'Postgrado' 'Ninguno'
 'No Aplica']
Columna: fami_educacionpadre , Valores Unicos: ['Secundaria (Bachillerato) incompleta'
 'Secundaria (Bachillerato) completa' 'Técnica o tecnológica completa'
 'No Aplica' 'Primaria completa' 'Primaria incompleta'
 'Educación profesional completa' 'No sabe'
 'Educación profesional incompleta' 'Técnica o tecnológica incompleta'
 'Ninguno' nan 'Postgrado']
Columna: fami_estratovivienda , Valores Unicos: ['Estrato 2' 'Estrato 3' 'Estrato 1' 'Estrato 4' nan 'Sin Estrato'
 'Estrato 6' 'Estrato 5']
Columna: fami_personashogar , Valores Unicos: ['5 a 6' '3 a 4' '9 o más' '1 a 2' '7 a 8' nan]
Columna: fami_tieneautomovil , Valores Unicos: ['No' 'Si' nan]
Columna: fami_tienecomputador , Valores Unicos: ['Si' 'No' nan]
Columna: fami_tieneinternet , Valores Unicos: ['Si' 'No' nan]
Columna: fami_tienelavadora , Valores Unicos: ['Si' 'No' nan]
Columna: desemp_ingles , Valores Unicos: ['A1' 'A-' 'A2' 'B1' 'B+' nan]
Columna: punt_ingles , Valores Unicos: ['56' '48' '42' '43' '62' '37' '50' '64' '66' '53' '57' '44' '54' '63'
 '46' '60' '49' '39' '52' '32' '68' '47' '51' '61' '38' '55' '82' '41'
 '34' '58' '74' '65' '59' '36' '73' '31' '78' '35' '67' '81' '76' '71'
 '33' '45' '77' '69' '40' '29' '70' '30' '72' '100' '75' '79' '80' '83'
 '85' '84' '0' '28' nan]
Columna: punt_matematicas , Valores Unicos: ['51' '45' '30' '62' '61' '52' '63' '75' '60' '55' '56' '54' '58' '48'
 '65' '42' '35' '47' '53' '59' '44' '38' '49' '43' '46' '76' '29' '64'
 '50' '57' '39' '66' '27' '41' '34' '31' '68' '67' '69' '32' '72' '70'
 '40' '33' '71' '26' '77' '78' '73' '80' '36' '37' '22' '74' '21' '28'
 '23' '24' '83' '82' '100' '79' '25' '81' '15' '84' '20' '17' '19' '18'
 '0' '16']
Columna: punt_sociales_ciudadanas , Valores Unicos: ['52' '49' '34' '37' '50' '58' '25' '41' '59' '57' '55' '60' '54' '46'
 '51' '53' '47' '68' '43' '48' '56' '40' '27' '42' '28' '61' '80' '64'
 '21' '70' '44' '62' '26' '35' '65' '63' '33' '45' '38' '32' '39' '73'
 '66' '36' '69' '31' '67' '71' '72' '74' '75' '30' '20' '77' '79' '76'
 '23' '24' '86' '29' '78' '84' '81' '82' '83' '85' '22' '100' '18' '19'
 '0']
Columna: punt_c_naturales , Valores Unicos: ['46' '39' '41' '54' '60' '48' '37' '62' '50' '56' '53' '52' '59' '49'
 '63' '55' '35' '61' '43' '44' '58' '38' '57' '45' '36' '42' '71' '67'
 '65' '32' '51' '40' '31' '47' '33' '64' '66' '69' '28' '34' '70' '68'
 '72' '76' '74' '29' '30' '75' '77' '80' '73' '100' '78' '81' '79' '27'
 '82' '25' '26' '24' '0']
Columna: punt_lectura_critica , Valores Unicos: ['59' '45' '55' '39' '66' '64' '37' '44' '60' '72' '61' '69' '56' '50'
 '57' '46' '68' '54' '48' '53' '58' '38' '67' '52' '47' '42' '65' '75'
 '63' '51' '43' '62' '31' '80' '70' '40' '33' '49' '74' '41' '71' '73'
 '36' '34' '76' '78' '32' '35' '0' '30' '29' '77' '100' '79' '81' '28'
 '26' '27' '82' '25' '83' '24']
Columna: punt_global , Valores Unicos: ['262' '239' '216' '186' '284' '304' '201' '212' '332' '295' '279' '238'
 '272' '268' '299' '274' '235' '269' '248' '322' '273' '270' '227' '232'
 '260' '257' '255' '264' '289' '296' '277' '230' '196' '294' '237' '253'
 '225' '265' '293' '259' '191' '251' '252' '287' '380' '306' '226' '158'
 '243' '343' '222' '267' '311' '197' '208' '229' '301' '228' '318' '292'
 '297' '223' '157' '249' '276' '244' '250' '278' '256' '286' '312' '221'
 '282' '207' '281' '182' '210' '236' '199' '245' '324' '362' '331' '261'
 '247' '316' '205' '258' '200' '285' '288' '254' '217' '345' '323' '204'
 '202' '327' '302' '308' '303' '309' '242' '240' '367' '190' '241' '305'
 '231' '246' '335' '214' '195' '188' '198' '189' '209' '313' '283' '317'
 '263' '215' '266' '213' '183' '321' '319' '307' '320' '280' '298' '328'
 '339' '350' '326' '218' '178' '203' '206' '310' '352' '290' '344' '358'
 '314' '361' '338' '233' '275' '347' '356' '315' '192' '220' '175' '193'
 '185' '187' '168' '341' '219' '172' '177' '180' '300' '211' '371' '333'
 '167' '291' '224' '325' '346' '336' '194' '184' '166' '360' '330' '348'
 '349' '174' '329' '340' '234' '109' '271' '354' '165' '162' '364' '163'
 '351' '342' '170' '161' '337' '381' '353' '378' '375' '368' '384' '374'
 '355' '405' '392' '365' '366' '372' '389' '400' '383' '173' '169' '164'
 '369' '171' '151' '181' '377' '397' '176' '334' '363' '359' '357' '376'
 '370' '411' '446' '407' '391' '388' '393' '179' '413' '373' '419' '386'
 '408' '403' '147' '385' '390' '423' '141' '160' '144' '398' '382' '406'
 '402' '395' '154' '436' '449' '379' '424' '409' '427' '401' '412' '387'
 '425' '417' '153' '422' '155' '156' '138' '437' '159' '414' '404' '420'
 '396' '438' '152' '146' '431' '150' '399' '418' '415' '394' '145' '440'
 '148' '416' '139' '410' '110' '143' '443' '445' '149' '430' '426' '142'
 '140' '428' '14' '135' '434' '421' '121' '450' '435' '131' '108' '116'
 '118' '128' '0']

Con esta validacion podemos ir determinando que variables se repiten en informacion o tienen pocos valores, lo que puede hacerla candidata de eliminacion posterior

### Outliers  o valores inesperados

In [11]:
for columna in df.columns:
    if df[columna].dtype == "object":
        print(f"\n{columna}:")
        print(df[columna].value_counts(dropna=False).head(20))

periodo:
periodo
20224    152584
Name: count, dtype: int64

estu_tipodocumento:
estu_tipodocumento
TI      131232
CC       18578
NES        814
CE         718
PEP        564
CR         542
PPT         68
PE          54
NUIP         6
RC           4
PC           4
Name: count, dtype: int64

estu_consecutivo:
estu_consecutivo
SB11202240071815    4
SB11202240072159    4
SB11202240072128    4
SB11202240072129    4
SB11202240072133    4
SB11202240072137    4
SB11202240072140    4
SB11202240072145    4
SB11202240072155    4
SB11202240072157    4
SB11202240071460    4
SB11202240072161    4
SB11202240072116    4
SB11202240072164    4
SB11202240072165    4
SB11202240072166    4
SB11202240072168    4
SB11202240072170    4
SB11202240071420    4
SB11202240072171    4
Name: count, dtype: int64

cole_area_ubicacion:
cole_area_ubicacion
URBANO    151258
RURAL       1326
Name: count, dtype: int64

cole_bilingue:
cole_bilingue
N      123762
NaN     28168
S         654
Name: count, dtype: int64

cole_calendario:
cole_calendario
A       151360
OTRO      1096
B          128
Name: count, dtype: int64

cole_caracter:
cole_caracter
ACADÉMICO            124824
TÉCNICO/ACADÉMICO     16184
NaN                    7036
TÉCNICO                2890
NO APLICA              1650
Name: count, dtype: int64

cole_cod_dane_establecimiento:
cole_cod_dane_establecimiento
111001024732    852
111001107875    794
111001030015    794
111001011819    792
111001010031    748
311001050023    736
111102000753    670
111001104281    654
111001076376    648
111001104329    606
111001106950    586
111001027391    582
111769003360    578
111850001428    574
111001010740    566
111001002909    540
111001036781    540
311001019053    536
111001107816    532
111001106968    530
Name: count, dtype: int64

cole_cod_dane_sede:
cole_cod_dane_sede
111001024732    852
111001107875    794
111001030015    794
111001011819    792
111001010031    748
311001050023    736
111102000753    670
111001104281    654
111001076376    648
111001104329    606
111001106950    586
111001027391    582
111850001428    574
111001010740    566
111001002909    540
111001036781    540
311001019053    536
111001107816    532
111001106968    530
111001083011    520
Name: count, dtype: int64

cole_cod_depto_ubicacion:
cole_cod_depto_ubicacion
11    152584
Name: count, dtype: int64

cole_cod_mcpio_ubicacion:
cole_cod_mcpio_ubicacion
11001    152584
Name: count, dtype: int64

cole_codigo_icfes:
cole_codigo_icfes
740506    736
023366    606
186106    566
019893    536
604769    506
724476    498
717330    490
745620    470
037150    458
720573    452
072934    444
019752    418
102632    408
140095    404
023820    398
088617    398
140103    390
735308    388
053926    376
664953    362
Name: count, dtype: int64

cole_depto_ubicacion:
cole_depto_ubicacion
BOGOTÁ    152584
Name: count, dtype: int64

cole_genero:
cole_genero
MIXTO        144332
FEMENINO       5408
MASCULINO      2844
Name: count, dtype: int64

cole_jornada:
cole_jornada
COMPLETA    47434
MAÑANA      39118
UNICA       30270
TARDE       24360
NOCHE        7212
SABATINA     4190
Name: count, dtype: int64

cole_mcpio_ubicacion:
cole_mcpio_ubicacion
BOGOTÁ D.C.    152584
Name: count, dtype: int64

cole_naturaleza:
cole_naturaleza
OFICIAL       87896
NO OFICIAL    64688
Name: count, dtype: int64

cole_nombre_establecimiento:
cole_nombre_establecimiento
COLEGIO TECNISISTEMAS                                                   1340
COLEGIO INEM FRANCISCO DE PAULA SANTANDER (IED)                          852
COLEGIO ENRIQUE OLAYA HERRERA (IED)                                      794
COLEGIO CIUDADELA EDUCATIVA DE BOSA (IED)                                794
COLEGIO LICEO FEMENINO MERCEDES NARIÑO (IED)                             792
COLEGIO CEDID SAN PABLO (IED)                                            748
COLEGIO DE EDUCACION TECNICA Y ACADEMICA CELESTIN FREINET                736
COLEGIO FERNANDO MAZUERA VILLEGAS (IED)                                  670
COLEGIO GABRIEL BETANCOURT MEJIA (IED)                                   654
COLEGIO MARRUECOS Y MOLINOS (IED)                                        648
COLEGIO CARLOS PIZARRO LEON GOMEZ (IED)                                  606
COLEGIO ALFONSO LOPEZ MICHELSEN (PUERTA DEL SOL) ( IED)                  586
COLEGIO MANUEL CEPEDA VARGAS (IED)                                       582
COLEGIO REPUBLICA DOMINICANA (IED)                                       578
COLEGIO ALMIRANTE PADILLA (IED)                                          574
COLEGIO INSTITUTO TECNICO INDUSTRIAL FRANCISCO JOSE DE CALDAS  (IED)     566
COLEGIO RODRIGO LARA BONILLA (IED)                                       540
COLEGIO CARLOS ALBAN HOLGUIN (IED)                                       540
COLEGIO CAFAM                                                            536
COLEGIO CUNDINAMARCA (IED)                                               532
Name: count, dtype: int64

cole_nombre_sede:
cole_nombre_sede
COLEGIO TECNISISTEMAS - SEDE PRINCIPAL                                                  1010
INEM FRANCISCO DE PAULA SANTANDER                                                        852
COL CUIDADELA EDUCATIVA BOSA (INS EDUC DIST)                                             794
COL DIST ENRIQUE OLAYA HERRERA                                                           794
LICEO FEMENINO MERCEDES NARIÑO                                                           792
CEDID SAN PABLO BOSA                                                                     748
COLEGIO DE EDUCACION TECNICA Y ACADEMICA CELESTIN FREINET - SEDE PRINCIPAL               736
COL DIST FERNANDO MAZUERA VILLEGAS                                                       670
COL GABRIEL BETANCOURT MEJIA (INST EDUC DIST)                                            654
CENT EDUC DIST MARRUECOS Y MOLINOS                                                       648
CARLOS PIZARRO LEON GOMEZ (INST EDUC DIST)                                               606
ALFONSO LÒPEZ MICHELSEN (PUERTA DEL SOL INST EDUC DIST)                                  586
COLEGIO MANUEL CEPEDA VARGAS (IED) - SEDE PRINCIPAL                                      582
CENT EDUC DIST ALMIRANTE PADILLA                                                         574
COLEGIO INSTITUTO TECNICO INDUSTRIAL FRANCISCO JOSE DE CALDAS (IED) - SEDE PRINCIPAL     566
SEDE B                                                                                   562
CENT EDUC DIST CARLOS ALBAN HOLGUIN                                                      540
COL DIST EDUC BAS Y MEDIA RODRIGO LARA BONILLA                                           540
COLEGIO CAFAM                                                                            536
COL CUNDINAMARCA (INS EDUC DIST)                                                         532
Name: count, dtype: int64

cole_sede_principal:
cole_sede_principal
S    147866
N      4718
Name: count, dtype: int64

estu_cod_depto_presentacion:
estu_cod_depto_presentacion
11    149766
25      1624
05       318
73       114
15        86
68        72
76        68
54        66
41        48
50        42
18        42
66        42
08        40
44        36
85        34
17        30
13        28
47        22
27        18
19        16
Name: count, dtype: int64

estu_cod_mcpio_presentacion:
estu_cod_mcpio_presentacion
11001    149766
25754       492
25175       282
25126       126
25430       120
25899        96
05376        94
25269        88
73001        78
25875        64
05001        62
25286        62
25473        58
76001        52
05042        42
25151        38
18001        36
25377        36
54001        32
68001        32
Name: count, dtype: int64

estu_cod_reside_depto:
estu_cod_reside_depto
11    149784
25      1724
05       302
73       100
15        76
68        66
76        60
54        58
08        42
41        42
18        38
66        34
44        34
50        32
85        32
17        26
13        20
47        16
27        16
63        14
Name: count, dtype: int64

estu_cod_reside_mcpio:
estu_cod_reside_mcpio
11001    149784
25754       612
25175       214
25430       116
25126       102
05376        92
25269        64
25286        64
73001        62
25875        62
25899        58
25473        54
05001        54
76001        44
05042        42
25214        42
18001        34
68001        30
08001        30
44847        30
Name: count, dtype: int64

estu_depto_presentacion:
estu_depto_presentacion
BOGOTÁ             149766
CUNDINAMARCA         1624
ANTIOQUIA             318
TOLIMA                114
BOYACA                 86
SANTANDER              72
VALLE                  68
NORTE SANTANDER        66
HUILA                  48
META                   42
CAQUETA                42
RISARALDA              42
ATLANTICO              40
LA GUAJIRA             36
CASANARE               34
CALDAS                 30
BOLIVAR                28
MAGDALENA              22
CHOCO                  18
CAUCA                  16
Name: count, dtype: int64

estu_depto_reside:
estu_depto_reside
BOGOTÁ             149784
CUNDINAMARCA         1724
ANTIOQUIA             302
TOLIMA                100
BOYACA                 76
SANTANDER              66
VALLE                  60
NORTE SANTANDER        58
ATLANTICO              42
HUILA                  42
CAQUETA                38
RISARALDA              34
LA GUAJIRA             34
META                   32
CASANARE               32
CALDAS                 26
BOLIVAR                20
MAGDALENA              16
CHOCO                  16
QUINDIO                14
Name: count, dtype: int64

estu_estadoinvestigacion:
estu_estadoinvestigacion
PUBLICAR                    152536
VALIDEZ OFICINA JURÍDICA        48
Name: count, dtype: int64

estu_estudiante:
estu_estudiante
ESTUDIANTE    152584
Name: count, dtype: int64

estu_fechanacimiento:
estu_fechanacimiento
05/10/2005    318
19/09/2005    316
05/09/2005    314
13/09/2005    304
10/10/2005    294
30/09/2005    294
18/10/2005    290
26/09/2005    288
29/09/2005    288
02/09/2005    288
29/08/2005    286
14/06/2005    286
08/09/2005    286
10/08/2005    284
29/12/2005    284
25/08/2005    284
23/08/2005    282
07/12/2005    280
03/08/2005    280
08/11/2005    280
Name: count, dtype: int64

estu_genero:
estu_genero
F    79844
M    72740
Name: count, dtype: int64

estu_mcpio_presentacion:
estu_mcpio_presentacion
BOGOTÁ D.C.              149766
SOACHA                      492
CHÍA                        282
CAJICÁ                      126
MADRID                      120
ZIPAQUIRÁ                    96
LA CEJA                      94
FACATATIVÁ                   88
IBAGUÉ                       78
VILLETA                      64
MEDELLÍN                     62
FUNZA                        62
MOSQUERA                     58
CALI                         52
SANTA FÉ DE ANTIOQUIA        42
CÁQUEZA                      38
FLORENCIA                    36
LA CALERA                    36
CÚCUTA                       32
BUCARAMANGA                  32
Name: count, dtype: int64

estu_mcpio_reside:
estu_mcpio_reside
BOGOTÁ D.C.              149784
SOACHA                      612
CHÍA                        214
MADRID                      116
CAJICÁ                      102
LA CEJA                      92
FUNZA                        64
FACATATIVÁ                   64
IBAGUÉ                       62
VILLETA                      62
ZIPAQUIRÁ                    58
MEDELLÍN                     54
MOSQUERA                     54
CALI                         44
COTA                         42
SANTA FÉ DE ANTIOQUIA        42
FLORENCIA                    34
URIBIA                       30
BUCARAMANGA                  30
BARRANQUILLA                 30
Name: count, dtype: int64

estu_nacionalidad:
estu_nacionalidad
COLOMBIA                150322
VENEZUELA                 2148
ECUADOR                     30
CHILE                       10
ESTADOS UNIDOS               8
ARGENTINA                    8
BRASIL                       6
GUATEMALA                    6
PERÚ                         4
COSTA RICA                   4
VANUATU                      4
CUBA                         4
ITALIA                       4
EL SALVADOR                  4
REPÚBLICA DOMINICANA         4
ESPAÑA                       2
CABO VERDE                   2
PORTUGAL                     2
MÉXICO                       2
COREA DEL SUR                2
Name: count, dtype: int64

estu_pais_reside:
estu_pais_reside
COLOMBIA                150322
VENEZUELA                 2148
ECUADOR                     30
CHILE                       10
ESTADOS UNIDOS               8
ARGENTINA                    8
BRASIL                       6
GUATEMALA                    6
PERÚ                         4
COSTA RICA                   4
VANUATU                      4
CUBA                         4
ITALIA                       4
EL SALVADOR                  4
REPÚBLICA DOMINICANA         4
ESPAÑA                       2
CABO VERDE                   2
PORTUGAL                     2
MÉXICO                       2
COREA DEL SUR                2
Name: count, dtype: int64

estu_privado_libertad:
estu_privado_libertad
N    152504
S        80
Name: count, dtype: int64

fami_cuartoshogar:
fami_cuartoshogar
Tres          63912
Dos           51326
Cuatro        18428
Cinco          5396
Uno            5170
NaN            4330
Seis o mas     4022
Name: count, dtype: int64

fami_educacionmadre:
fami_educacionmadre
Secundaria (Bachillerato) completa      42430
Educación profesional completa          24520
Secundaria (Bachillerato) incompleta    18402
Técnica o tecnológica completa          17670
Primaria incompleta                      9518
Primaria completa                        8536
Técnica o tecnológica incompleta         7130
Postgrado                                6662
Educación profesional incompleta         6184
NaN                                      6088
No sabe                                  4022
Ninguno                                  1078
No Aplica                                 344
Name: count, dtype: int64

fami_educacionpadre:
fami_educacionpadre
Secundaria (Bachillerato) completa      40308
Secundaria (Bachillerato) incompleta    21626
Educación profesional completa          18130
Primaria incompleta                     13856
No sabe                                 12004
Técnica o tecnológica completa          11406
Primaria completa                        9470
NaN                                      6108
Postgrado                                5162
Técnica o tecnológica incompleta         4992
Educación profesional incompleta         4680
No Aplica                                2826
Ninguno                                  2016
Name: count, dtype: int64

fami_estratovivienda:
fami_estratovivienda
Estrato 2      62920
Estrato 3      52628
Estrato 1      14838
Estrato 4      11412
NaN             6514
Estrato 5       2326
Sin Estrato     1112
Estrato 6        834
Name: count, dtype: int64

fami_personashogar:
fami_personashogar
3 a 4      83860
5 a 6      38652
1 a 2      14794
7 a 8       7746
NaN         4124
9 o más     3408
Name: count, dtype: int64

fami_tieneautomovil:
fami_tieneautomovil
No     93328
Si     54910
NaN     4346
Name: count, dtype: int64

fami_tienecomputador:
fami_tienecomputador
Si     117884
No      30570
NaN      4130
Name: count, dtype: int64

fami_tieneinternet:
fami_tieneinternet
Si     135816
No      10568
NaN      6200
Name: count, dtype: int64

fami_tienelavadora:
fami_tienelavadora
Si     135272
No      13130
NaN      4182
Name: count, dtype: int64

desemp_ingles:
desemp_ingles
A1     44752
A-     42514
A2     35204
B1     23412
B+      6672
NaN       30
Name: count, dtype: int64

punt_ingles:
punt_ingles
56    4976
55    4926
57    4924
54    4872
58    4808
53    4700
52    4662
59    4352
51    4190
50    4148
61    3840
60    3832
49    3772
48    3582
62    3522
47    3270
63    3244
46    3236
64    3202
45    3186
Name: count, dtype: int64

punt_matematicas:
punt_matematicas
54    5506
56    5490
57    5338
58    5330
60    5316
53    5268
55    5266
59    5188
52    5168
51    4998
61    4896
62    4744
50    4732
63    4542
49    4484
48    4180
64    4028
47    4024
65    3710
46    3624
Name: count, dtype: int64

punt_sociales_ciudadanas:
punt_sociales_ciudadanas
55    4956
56    4852
54    4790
59    4696
57    4684
53    4666
52    4658
58    4618
51    4472
60    4436
49    4432
50    4364
47    4350
61    4304
62    4300
48    4134
46    4060
44    3912
63    3882
45    3858
Name: count, dtype: int64

punt_c_naturales:
punt_c_naturales
51    5696
53    5496
50    5492
49    5454
52    5414
54    5376
56    5312
48    5196
55    5132
47    5122
57    5024
46    4970
58    4944
59    4860
45    4726
60    4470
44    4442
43    4376
61    4136
42    4118
Name: count, dtype: int64

punt_lectura_critica:
punt_lectura_critica
59    6110
60    6106
58    6080
57    5858
56    5804
61    5730
62    5552
55    5508
54    5474
63    5352
64    5330
53    5274
65    5012
52    4992
51    4782
66    4506
50    4476
49    4256
67    4248
48    3936
Name: count, dtype: int64

punt_global:
punt_global
277    1410
273    1352
270    1334
250    1332
275    1328
265    1320
278    1318
287    1312
280    1290
292    1288
267    1280
257    1276
268    1272
262    1272
272    1266
243    1266
282    1256
260    1246
293    1240
288    1240
Name: count, dtype: int64

In [12]:
#validacion de puntajes
columnas_puntajes = [
    "punt_global",
    "punt_matematicas",
    "punt_sociales_ciudadanas",
    "punt_c_naturales",
    "punt_lectura_critica",
    "punt_ingles"
]

for columna in columnas_puntajes:
    puntajes = pd.to_numeric(df[columna], errors="coerce")

    print(f"\n{columna}")
    print("Mínimo:", puntajes.min())
    print("Máximo:", puntajes.max())
    print("Valores negativos:", (puntajes < 0).sum())
    print("Valores no numéricos:", (puntajes.isna() & df[columna].notna()).sum())

punt_global
Mínimo: 0
Máximo: 450
Valores negativos: 0
Valores no numéricos: 0

punt_matematicas
Mínimo: 0
Máximo: 100
Valores negativos: 0
Valores no numéricos: 0

punt_sociales_ciudadanas
Mínimo: 0
Máximo: 100
Valores negativos: 0
Valores no numéricos: 0

punt_c_naturales
Mínimo: 0
Máximo: 100
Valores negativos: 0
Valores no numéricos: 0

punt_lectura_critica
Mínimo: 0
Máximo: 100
Valores negativos: 0
Valores no numéricos: 0

punt_ingles
Mínimo: 0.0
Máximo: 100.0
Valores negativos: 0
Valores no numéricos: 0

Se confirma que variables como fecha de nacimiento es correcta y que los rangos en puntajes es el esperado

## Descarga Base Inicial

Se realiza descarga para guardar la primera version de los datos en DVC

In [13]:
df.to_csv("Saber11_2022.csv", index=False, encoding = "utf-8-sig")

In [14]:
print("Base original guardada.")
print(f"Registros originales: {len(df):,}")
print(f"Columnas originales: {df.shape[1]}")

Base original guardada.
Registros originales: 152,584
Columnas originales: 51

# Limpieza de Datos

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
sns.set_theme(style="whitegrid")

## Eliminación de duplicados

In [16]:
print("Total de registros:", len(df))

print(
    "Estudiantes únicos:",
    df["estu_consecutivo"].nunique()
)

print(
    "Identificadores nulos:",
    df["estu_consecutivo"].isna().sum()
)

print(
    "Filas completamente duplicadas:",
    df.duplicated().sum()
)

Total de registros: 152584
Estudiantes únicos: 76253
Identificadores nulos: 0
Filas completamente duplicadas: 76331

En primer lugar y dado que se comprueba que los registro con el código de estudiante vienen desde la importación de los datos procedemos a eliminar los registros duplicados:

In [17]:
if "punt_global" not in df.columns:
    raise KeyError("No existe la columna 'punt_global' en la base.")

dffinal = df.loc[
    df["punt_global"].notna()
].copy()

print("\nELIMINACIÓN DE REGISTROS SIN PUNTAJE GLOBAL")
print(f"Registros iniciales: {len(dffinal):,}")
print(f"Registros sin puntaje global: {dffinal['punt_global'].isna().sum():,}")
print(f"Registros conservados: {len(dffinal):,}")

ELIMINACIÓN DE REGISTROS SIN PUNTAJE GLOBAL
Registros iniciales: 152,584
Registros sin puntaje global: 0
Registros conservados: 152,584

In [18]:
duplicados_eliminados = dffinal.duplicated().sum()

dffinal = dffinal.drop_duplicates().copy()

print("\nELIMINACIÓN DE DUPLICADOS EXACTOS")
print(f"Duplicados exactos eliminados: {duplicados_eliminados:,}")
print(f"Registros después de eliminar duplicados: {len(dffinal):,}")

ELIMINACIÓN DE DUPLICADOS EXACTOS
Duplicados exactos eliminados: 76,331
Registros después de eliminar duplicados: 76,253

In [19]:
dffinal.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76253 entries, 0 to 152582
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   periodo                        76253 non-null  object
 1   estu_tipodocumento             76253 non-null  object
 2   estu_consecutivo               76253 non-null  object
 3   cole_area_ubicacion            76253 non-null  object
 4   cole_bilingue                  62169 non-null  object
 5   cole_calendario                76253 non-null  object
 6   cole_caracter                  72735 non-null  object
 7   cole_cod_dane_establecimiento  76253 non-null  object
 8   cole_cod_dane_sede             76253 non-null  object
 9   cole_cod_depto_ubicacion       76253 non-null  object
 10  cole_cod_mcpio_ubicacion       76253 non-null  object
 11  cole_codigo_icfes              76253 non-null  object
 12  cole_depto_ubicacion           76253 non-null  object
 13  cole_genero                    76253 non-null  object
 14  cole_jornada                   76253 non-null  object
 15  cole_mcpio_ubicacion           76253 non-null  object
 16  cole_naturaleza                76253 non-null  object
 17  cole_nombre_establecimiento    76253 non-null  object
 18  cole_nombre_sede               76253 non-null  object
 19  cole_sede_principal            76253 non-null  object
 20  estu_cod_depto_presentacion    76253 non-null  object
 21  estu_cod_mcpio_presentacion    76253 non-null  object
 22  estu_cod_reside_depto          76253 non-null  object
 23  estu_cod_reside_mcpio          76253 non-null  object
 24  estu_depto_presentacion        76253 non-null  object
 25  estu_depto_reside              76253 non-null  object
 26  estu_estadoinvestigacion       76253 non-null  object
 27  estu_estudiante                76253 non-null  object
 28  estu_fechanacimiento           76253 non-null  object
 29  estu_genero                    76253 non-null  object
 30  estu_mcpio_presentacion        76253 non-null  object
 31  estu_mcpio_reside              76253 non-null  object
 32  estu_nacionalidad              76253 non-null  object
 33  estu_pais_reside               76253 non-null  object
 34  estu_privado_libertad          76253 non-null  object
 35  fami_cuartoshogar              74088 non-null  object
 36  fami_educacionmadre            73212 non-null  object
 37  fami_educacionpadre            73202 non-null  object
 38  fami_estratovivienda           72999 non-null  object
 39  fami_personashogar             74191 non-null  object
 40  fami_tieneautomovil            74080 non-null  object
 41  fami_tienecomputador           74188 non-null  object
 42  fami_tieneinternet             73156 non-null  object
 43  fami_tienelavadora             74162 non-null  object
 44  desemp_ingles                  76238 non-null  object
 45  punt_ingles                    76238 non-null  object
 46  punt_matematicas               76253 non-null  object
 47  punt_sociales_ciudadanas       76253 non-null  object
 48  punt_c_naturales               76253 non-null  object
 49  punt_lectura_critica           76253 non-null  object
 50  punt_global                    76253 non-null  object
dtypes: object(51)
memory usage: 30.3+ MB

## Eliminación de columnas no requeridas para el modelo

Descartaremos las columnas relacionadas con códigos de identificación (DANE // colegio) dado que podemos asociarlas por el nombre del código que representan:
- estu_tipodocumento
- estu_consecutivo
- estu_estadoinvestigacion
- cole_cod_dane_establecimiento  
- cole_cod_dane_sede  
- cole_cod_depto_ubicacion  
- cole_cod_mcpio_ubicacion  
- estu_cod_reside_depto  
- estu_cod_reside_mcpio
- estu_cod_reside_depto
- estu_cod_reside_mcpio
- cole_codigo_icfes - se descarta puesto que es un identificador de cada colegio

Adicionalmente eliminaremos las variables relacionadas con información sobre los colegios teniendo en consideración que no brinda información adicional con relación a la identificación del colegio principal:

- cole_nombre_establecimiento  
- cole_nombre_sede  
- cole_sede_principal

Eliminaremos la variable **Estu_estudiante** dado que solo contiene un valor unico, la variable cole_cod_mcpio_ubicacion dado que todos los estudiantes son de Bogotá.

Prescindiremos de la columna estu_fechanacimiento dado que el rango de edad de los estudiantes por la naturaleza del evento no deberia presentar variaciones significativas.

Sumado a esto, descartaremos las variables: estu_depto_reside, estu_pais_reside, estu_depto_presentacion, estu_mcpio_presentacion, estu_mcpio_reside, estu_nacionalidad teniendo en cuenta que el enfoque de estudio está orientado a estudiantes de colegios ubicados en la ciudad de Bogotá.

In [21]:
# Quitar columnas:
columnas_a_quitar = ['estu_tipodocumento','estu_fechanacimiento','estu_consecutivo','cole_mcpio_ubicacion','estu_estadoinvestigacion','cole_cod_dane_establecimiento', 'cole_cod_dane_sede','cole_cod_depto_ubicacion','cole_cod_mcpio_ubicacion','estu_cod_reside_depto','estu_cod_reside_mcpio','estu_cod_reside_depto','estu_cod_depto_presentacion','estu_cod_mcpio_presentacion','estu_cod_reside_mcpio','cole_codigo_icfes','cole_nombre_establecimiento','cole_nombre_sede','cole_sede_principal','estu_estudiante','cole_depto_ubicacion','estu_depto_presentacion','cole_cod_mcpio_ubicacion','estu_pais_reside','estu_mcpio_reside','estu_mcpio_presentacion','estu_depto_reside','estu_nacionalidad','estu_privado_libertad']
dffinal.drop(columns=columnas_a_quitar, inplace=True)

In [22]:
dffinal.shape

(76253, 25)

In [23]:
for columna in dffinal.columns:
    print(columna)

periodo
cole_area_ubicacion
cole_bilingue
cole_calendario
cole_caracter
cole_genero
cole_jornada
cole_naturaleza
estu_genero
fami_cuartoshogar
fami_educacionmadre
fami_educacionpadre
fami_estratovivienda
fami_personashogar
fami_tieneautomovil
fami_tienecomputador
fami_tieneinternet
fami_tienelavadora
desemp_ingles
punt_ingles
punt_matematicas
punt_sociales_ciudadanas
punt_c_naturales
punt_lectura_critica
punt_global

Pasamos de tener 51 variables a 25 con información relevante para el modelo

## Tratamiento de nulos

In [24]:
resumen_nulos = pd.DataFrame({
    "nulos": dffinal.isna().sum(),
    "porcentaje_nulos": (dffinal.isna().mean() * 100).round(2)
})

resumen_nulos = resumen_nulos.query("nulos > 0")
resumen_nulos = resumen_nulos.sort_values(
    "porcentaje_nulos",
    ascending=False
)

display(resumen_nulos)

                      nulos  porcentaje_nulos
cole_bilingue         14084             18.47
cole_caracter          3518              4.61
fami_estratovivienda   3254              4.27
fami_tieneinternet     3097              4.06
fami_educacionpadre    3051              4.00
fami_educacionmadre    3041              3.99
fami_tieneautomovil    2173              2.85
fami_cuartoshogar      2165              2.84
fami_tienelavadora     2091              2.74
fami_tienecomputador   2065              2.71
fami_personashogar     2062              2.70
desemp_ingles            15              0.02
punt_ingles              15              0.02

In [25]:
# Variables categóricas del colegio: imputar moda si existe.
columnas_moda = ["cole_caracter","cole_bilingue","fami_estratovivienda","desemp_ingles"]

for columna in columnas_moda:
    if columna in dffinal.columns and dffinal[columna].notna().any():
        moda = dffinal[columna].mode(dropna=True)

        if not moda.empty:
            dffinal[columna] = dffinal[columna].fillna(moda.iloc[0])


# Género: identificar los faltantes sin asignarles una categoría real.
if "estu_genero" in dffinal.columns:
    dffinal["estu_genero"] = (dffinal["estu_genero"].fillna("N.D."))


# Variables de posesiones del hogar.
# No se asume que la ausencia de respuesta signifique "No".
columnas_posesiones = ["fami_tieneautomovil","fami_tienecomputador","fami_tieneinternet","fami_tienelavadora"]

for columna in columnas_posesiones:
    if columna in dffinal.columns:
        dffinal[columna] = (dffinal[columna].fillna("No informa"))


# Educación de madre y padre.
for columna in ["fami_educacionmadre", "fami_educacionpadre"]:
    if columna in dffinal.columns:
        dffinal[columna] = (dffinal[columna].fillna("No sabe"))


# Variables familiares con categorías de cantidad.
for columna in ["fami_cuartoshogar", "fami_personashogar"]:
    if columna in dffinal.columns:
        dffinal[columna] = (dffinal[columna].fillna("No informa"))

In [26]:
if "fami_cuartoshogar" in dffinal.columns:
    reemplazos_cuartos = {"Seis": "Seis o más","Siete": "Seis o más","Ocho": "Seis o más","Nueve": "Seis o más","Diez o más": "Seis o más"}
    dffinal["fami_cuartoshogar"] = (dffinal["fami_cuartoshogar"].replace(reemplazos_cuartos))


# Agrupar tamaños del hogar.
if "fami_personashogar" in dffinal.columns:
    reemplazos_personas = {"Una": "1 a 2","Dos": "1 a 2","Tres": "3 a 4","Cuatro": "3 a 4","Cinco": "5 a 6","Seis": "5 a 6","Siete": "7 a 8","Ocho": "7 a 8","Nueve": "9 o más","Diez": "9 o más","Once": "9 o más","Doce o más": "9 o más"}

    dffinal["fami_personashogar"] = (dffinal["fami_personashogar"].replace(reemplazos_personas))

In [27]:
resumen_nulos = pd.DataFrame({
    "nulos": dffinal.isna().sum(),
    "porcentaje_nulos": (dffinal.isna().mean() * 100).round(2)
})

resumen_nulos = resumen_nulos.query("nulos > 0")
resumen_nulos = resumen_nulos.sort_values(
    "porcentaje_nulos",
    ascending=False
)

display(resumen_nulos)

             nulos  porcentaje_nulos
punt_ingles     15              0.02

In [28]:
display(dffinal["punt_ingles"].unique())

array(['56', '48', '42', '43', '62', '37', '50', '64', '66', '53', '57',
       '44', '54', '63', '46', '60', '49', '39', '52', '32', '68', '47',
       '51', '61', '38', '55', '82', '41', '34', '58', '74', '65', '59',
       '36', '73', '31', '78', '35', '67', '81', '76', '71', '33', '45',
       '77', '69', '40', '29', '70', '30', '72', '100', '75', '79', '80',
       '83', '85', '84', '0', '28', nan], dtype=object)

Antes de imputar el promedio  en esta columna vamos a convertir correctamente los tipos de cada una:

In [29]:
#Definir el tipo de cada variable:
dffinal['periodo'] = dffinal['periodo'].astype('category')

columnas_category = [
    'cole_area_ubicacion',
    'cole_bilingue',
    'cole_calendario',
    'cole_caracter',
    'cole_genero',
    'cole_jornada',
    'cole_naturaleza',    
    'estu_genero',
    'fami_cuartoshogar',
    'fami_educacionmadre',
    'fami_educacionpadre',
    'fami_estratovivienda',
    'fami_personashogar',
    'fami_tieneautomovil',
    'fami_tienecomputador',
    'fami_tieneinternet',
    'fami_tienelavadora',
    'desemp_ingles'
]
for col in columnas_category:
    dffinal[col] = dffinal[col].astype('category')

columnas_int = [
    'punt_ingles',
    'punt_matematicas',
    'punt_sociales_ciudadanas',
    'punt_c_naturales',
    'punt_lectura_critica',
    'punt_global'
]
for col in columnas_int:
    dffinal[col] = pd.to_numeric(dffinal[col], errors='coerce').astype('Int64')

In [30]:
dffinal.dtypes

periodo                     category
cole_area_ubicacion         category
cole_bilingue               category
cole_calendario             category
cole_caracter               category
cole_genero                 category
cole_jornada                category
cole_naturaleza             category
estu_genero                 category
fami_cuartoshogar           category
fami_educacionmadre         category
fami_educacionpadre         category
fami_estratovivienda        category
fami_personashogar          category
fami_tieneautomovil         category
fami_tienecomputador        category
fami_tieneinternet          category
fami_tienelavadora          category
desemp_ingles               category
punt_ingles                    Int64
punt_matematicas               Int64
punt_sociales_ciudadanas       Int64
punt_c_naturales               Int64
punt_lectura_critica           Int64
punt_global                    Int64
dtype: object

In [31]:
resumen_nulos = pd.DataFrame({
    "nulos": dffinal.isna().sum(),
    "porcentaje_nulos": (dffinal.isna().mean() * 100).round(2)
})

resumen_nulos = resumen_nulos.query("nulos > 0")
resumen_nulos = resumen_nulos.sort_values(
    "porcentaje_nulos",
    ascending=False
)

display(resumen_nulos)

             nulos  porcentaje_nulos
punt_ingles     15              0.02

In [32]:
promedio_ingles = int(round(dffinal["punt_ingles"].mean()))
dffinal["punt_ingles"] = dffinal["punt_ingles"].fillna(promedio_ingles)
print("Promedio utilizado:", promedio_ingles)
print("Tipo de dato:", dffinal["punt_ingles"].dtype)
print("Nulos restantes:", dffinal["punt_ingles"].isna().sum())

Promedio utilizado: 56
Tipo de dato: Int64
Nulos restantes: 0

Finalmente, se cuenta con una base depurada de 76.253 registros y 25 variables:

In [33]:
dffinal.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76253 entries, 0 to 152582
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   periodo                   76253 non-null  category
 1   cole_area_ubicacion       76253 non-null  category
 2   cole_bilingue             76253 non-null  category
 3   cole_calendario           76253 non-null  category
 4   cole_caracter             76253 non-null  category
 5   cole_genero               76253 non-null  category
 6   cole_jornada              76253 non-null  category
 7   cole_naturaleza           76253 non-null  category
 8   estu_genero               76253 non-null  category
 9   fami_cuartoshogar         76253 non-null  category
 10  fami_educacionmadre       76253 non-null  category
 11  fami_educacionpadre       76253 non-null  category
 12  fami_estratovivienda      76253 non-null  category
 13  fami_personashogar        76253 non-null  category
 14  fami_tieneautomovil       76253 non-null  category
 15  fami_tienecomputador      76253 non-null  category
 16  fami_tieneinternet        76253 non-null  category
 17  fami_tienelavadora        76253 non-null  category
 18  desemp_ingles             76253 non-null  category
 19  punt_ingles               76253 non-null  Int64
 20  punt_matematicas          76253 non-null  Int64
 21  punt_sociales_ciudadanas  76253 non-null  Int64
 22  punt_c_naturales          76253 non-null  Int64
 23  punt_lectura_critica      76253 non-null  Int64
 24  punt_global               76253 non-null  Int64
dtypes: Int64(6), category(19)
memory usage: 5.9 MB

# Análisis descriptivo y exploración gráfica - Kevin

# Relaciones entre variables y hallazgos exploratorios - Andrés