### Proyecto Despliegue Soluciones Analiticas

Presentado por:
- Laura Marcela Ramirez Casallas
- Kevin Alejandro Caicedo Rodriguez
- Jhon Jairo Meneses Prieto
- Jeferson Andrés Gutiérrez Gutiérrez

## Pregunta de Negocio


El examen **saber 11°** es una prueba utilizada por el instituto colombiano para la evaluación de la Educación (ICFES)1, para realizar mediciones oficiales acerca de la calidad del servicio educativo prestado a nivel nacional. Esta prueba es practicada a los estudiantes de todos los establecimientos educativos, privados y públicos, que están terminando su formación académica media (grado 11, previo a iniciar la formación universitaria). 

Con este contexto, el problema que vamos a abordar se enfoca en entender cuáles son los factores o variables que inciden en los resultados obtenidos por cada estudiante con el fin de enfocar el uso de los recursos disponibles para implementar políticas públicas que busquen fortalecer las competencias de los estudiantes del país. 

Por tal razón, bajo este contexto, la pregunta de negocio es la siguiente:

#### *¿Cómo puede la secretaria de educacion lograr el aumento de la aprobación del ICFES mediante el análisis de variables demográficas, socioeconómicos e institucionales para identificar brechas de rendimiento y mejorar la calidad educativa de cada una de las instituciones analizadas de la ciudad de Bogotá?*

## Fuente de los datos

Para dar solución al caso de estudio contamos con los datos publicados a través de la plataforma de Datos Abiertos de Colombia, a los que se puede acceder a través del siguiente URL: 

https://www.datos.gov.co/en/Educaci-n/Bogota_historico_saber_11/8qwp-pzhz/about_data

## Importación de Datos

In [2]:
pip install Sodapy

Requirement already satisfied: Sodapy in d:\johnm\programas\anaconda\lib\site-packages (2.2.0)
Requirement already satisfied: requests>=2.28.1 in d:\johnm\programas\anaconda\lib\site-packages (from Sodapy) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\johnm\programas\anaconda\lib\site-packages (from requests>=2.28.1->Sodapy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\johnm\programas\anaconda\lib\site-packages (from requests>=2.28.1->Sodapy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\johnm\programas\anaconda\lib\site-packages (from requests>=2.28.1->Sodapy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\johnm\programas\anaconda\lib\site-packages (from requests>=2.28.1->Sodapy) (2026.4.22)
Note: you may need to restart the kernel to use updated packages.

Vamos a utilizar el año 2022, que es el mas reciente y el que surge luego de pandemia

In [22]:
from sodapy import Socrata
import pandas as pd

APP_TOKEN = "zkj4BAQIZkr7n4t4NKzvLt5zq"
client = Socrata("datos.gov.co", APP_TOKEN, timeout=120)

dataset_id = "8qwp-pzhz"
periodo_objetivo = 20224

# parámetros
limit = 50000   # máximo permitido por Socrata en una llamada
offset = 0
all_results = []

while True:
    results = client.get(
        dataset_id,
        where=f"periodo = '{periodo_objetivo}'",
        limit=limit,
        offset=offset
    )
    if not results:
        break
    all_results.extend(results)
    offset += limit
    print(f"Descargados {len(all_results)} registros...")

# convertir a DataFrame
df = pd.DataFrame.from_records(all_results)

print("Total de registros descargados:", len(df))

Descargados 50000 registros...
Descargados 100000 registros...
Descargados 150000 registros...
Descargados 152584 registros...
Total de registros descargados: 152584

In [23]:
print(df.shape)
display(df.head())
display(df.info())
display(df.describe(include="all").T)

(152584, 51)

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,TI,SB11202240162649,URBANO,N,A,ACADÉMICO,311848002271,311848002271,11,...,Si,Si,Si,B+,80,80,83,71,78,391
1,20224,CC,SB11202240538873,URBANO,N,A,ACADÉMICO,111850001428,111850001428,11,...,No,NaN,No,A-,32,39,45,39,44,205
2,20224,TI,SB11202240109844,URBANO,N,A,TÉCNICO/ACADÉMICO,111001013129,111001013129,11,...,No,Si,Si,A1,48,45,32,35,47,202
3,20224,NES,SB11202240192934,URBANO,N,A,ACADÉMICO,211850000051,211850000051,11,...,Si,Si,No,A2,59,71,62,68,79,346
4,20224,TI,SB11202240024287,URBANO,N,A,ACADÉMICO,311001092907,311001092907,11,...,Si,Si,No,A-,47,39,44,46,60,236

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152584 entries, 0 to 152583
Data columns (total 51 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   periodo                        152584 non-null  object
 1   estu_tipodocumento             152584 non-null  object
 2   estu_consecutivo               152584 non-null  object
 3   cole_area_ubicacion            152584 non-null  object
 4   cole_bilingue                  124416 non-null  object
 5   cole_calendario                152584 non-null  object
 6   cole_caracter                  145548 non-null  object
 7   cole_cod_dane_establecimiento  152584 non-null  object
 8   cole_cod_dane_sede             152584 non-null  object
 9   cole_cod_depto_ubicacion       152584 non-null  object
 10  cole_cod_mcpio_ubicacion       152584 non-null  object
 11  cole_codigo_icfes              152584 non-null  object
 12  cole_depto_ubicacion           152584 non-null  object
 13  cole_genero                    152584 non-null  object
 14  cole_jornada                   152584 non-null  object
 15  cole_mcpio_ubicacion           152584 non-null  object
 16  cole_naturaleza                152584 non-null  object
 17  cole_nombre_establecimiento    152584 non-null  object
 18  cole_nombre_sede               152584 non-null  object
 19  cole_sede_principal            152584 non-null  object
 20  estu_cod_depto_presentacion    152584 non-null  object
 21  estu_cod_mcpio_presentacion    152584 non-null  object
 22  estu_cod_reside_depto          152584 non-null  object
 23  estu_cod_reside_mcpio          152584 non-null  object
 24  estu_depto_presentacion        152584 non-null  object
 25  estu_depto_reside              152584 non-null  object
 26  estu_estadoinvestigacion       152584 non-null  object
 27  estu_estudiante                152584 non-null  object
 28  estu_fechanacimiento           152584 non-null  object
 29  estu_genero                    152584 non-null  object
 30  estu_mcpio_presentacion        152584 non-null  object
 31  estu_mcpio_reside              152584 non-null  object
 32  estu_nacionalidad              152584 non-null  object
 33  estu_pais_reside               152584 non-null  object
 34  estu_privado_libertad          152584 non-null  object
 35  fami_cuartoshogar              148254 non-null  object
 36  fami_educacionmadre            146496 non-null  object
 37  fami_educacionpadre            146476 non-null  object
 38  fami_estratovivienda           146070 non-null  object
 39  fami_personashogar             148460 non-null  object
 40  fami_tieneautomovil            148238 non-null  object
 41  fami_tienecomputador           148454 non-null  object
 42  fami_tieneinternet             146384 non-null  object
 43  fami_tienelavadora             148402 non-null  object
 44  desemp_ingles                  152554 non-null  object
 45  punt_ingles                    152554 non-null  object
 46  punt_matematicas               152584 non-null  object
 47  punt_sociales_ciudadanas       152584 non-null  object
 48  punt_c_naturales               152584 non-null  object
 49  punt_lectura_critica           152584 non-null  object
 50  punt_global                    152584 non-null  object
dtypes: object(51)
memory usage: 59.4+ MB

None

,count,unique,top,freq
periodo,152584,1,20224,152584
estu_tipodocumento,152584,11,TI,131232
estu_consecutivo,152584,76253,SB11202240072129,4
cole_area_ubicacion,152584,2,URBANO,151258
cole_bilingue,124416,2,N,123762
cole_calendario,152584,3,A,151360
cole_caracter,145548,4,ACADÉMICO,124824
cole_cod_dane_establecimiento,152584,1131,111001024732,852
cole_cod_dane_sede,152584,1143,111001024732,852
cole_cod_depto_ubicacion,152584,1,11,152584
cole_cod_mcpio_ubicacion,152584,1,11001,152584
cole_codigo_icfes,152584,1460,740506,736
cole_depto_ubicacion,152584,1,BOGOTÁ,152584
cole_genero,152584,3,MIXTO,144332
cole_jornada,152584,6,COMPLETA,47434
cole_mcpio_ubicacion,152584,1,BOGOTÁ D.C.,152584
cole_naturaleza,152584,2,OFICIAL,87896
cole_nombre_establecimiento,152584,1111,COLEGIO TECNISISTEMAS,1340
cole_nombre_sede,152584,1125,COLEGIO TECNISISTEMAS - SEDE PRINCIPAL,1010
cole_sede_principal,152584,2,S,147866
estu_cod_depto_presentacion,152584,31,11,149766
estu_cod_mcpio_presentacion,152584,171,11001,149766
estu_cod_reside_depto,152584,30,11,149784
estu_cod_reside_mcpio,152584,206,11001,149784
estu_depto_presentacion,152584,31,BOGOTÁ,149766
estu_depto_reside,152584,30,BOGOTÁ,149784
estu_estadoinvestigacion,152584,2,PUBLICAR,152536
estu_estudiante,152584,1,ESTUDIANTE,152584
estu_fechanacimiento,152584,3692,05/10/2005,318
estu_genero,152584,2,F,79844
estu_mcpio_presentacion,152584,170,BOGOTÁ D.C.,149766
estu_mcpio_reside,152584,205,BOGOTÁ D.C.,149784
estu_nacionalidad,152584,24,COLOMBIA,150322
estu_pais_reside,152584,24,COLOMBIA,150322
estu_privado_libertad,152584,2,N,152504
fami_cuartoshogar,148254,6,Tres,63912
fami_educacionmadre,146496,12,Secundaria (Bachillerato) completa,42430
fami_educacionpadre,146476,12,Secundaria (Bachillerato) completa,40308
fami_estratovivienda,146070,7,Estrato 2,62920
fami_personashogar,148460,5,3 a 4,83860
fami_tieneautomovil,148238,2,No,93328
fami_tienecomputador,148454,2,Si,117884
fami_tieneinternet,146384,2,Si,135816
fami_tienelavadora,148402,2,Si,135272
desemp_ingles,152554,5,A1,44752
punt_ingles,152554,60,56,4976
punt_matematicas,152584,72,54,5506
punt_sociales_ciudadanas,152584,71,55,4956
punt_c_naturales,152584,61,51,5696
punt_lectura_critica,152584,62,59,6110
punt_global,152584,315,277,1410

In [ ]:
df.he

## Calidad de datos

### Nulos x columnas

In [29]:
for columna in df.columns:
    nulos = df[columna].isnull().sum()
    porcentaje = (nulos / len(df)) * 100

    print(f"{columna}: {nulos} nulos ({porcentaje:.2f}%)")

periodo: 0 nulos (0.00%)
estu_tipodocumento: 0 nulos (0.00%)
estu_consecutivo: 0 nulos (0.00%)
cole_area_ubicacion: 0 nulos (0.00%)
cole_bilingue: 28168 nulos (18.46%)
cole_calendario: 0 nulos (0.00%)
cole_caracter: 7036 nulos (4.61%)
cole_cod_dane_establecimiento: 0 nulos (0.00%)
cole_cod_dane_sede: 0 nulos (0.00%)
cole_cod_depto_ubicacion: 0 nulos (0.00%)
cole_cod_mcpio_ubicacion: 0 nulos (0.00%)
cole_codigo_icfes: 0 nulos (0.00%)
cole_depto_ubicacion: 0 nulos (0.00%)
cole_genero: 0 nulos (0.00%)
cole_jornada: 0 nulos (0.00%)
cole_mcpio_ubicacion: 0 nulos (0.00%)
cole_naturaleza: 0 nulos (0.00%)
cole_nombre_establecimiento: 0 nulos (0.00%)
cole_nombre_sede: 0 nulos (0.00%)
cole_sede_principal: 0 nulos (0.00%)
estu_cod_depto_presentacion: 0 nulos (0.00%)
estu_cod_mcpio_presentacion: 0 nulos (0.00%)
estu_cod_reside_depto: 0 nulos (0.00%)
estu_cod_reside_mcpio: 0 nulos (0.00%)
estu_depto_presentacion: 0 nulos (0.00%)
estu_depto_reside: 0 nulos (0.00%)
estu_estadoinvestigacion: 0 nulos (0.00%)
estu_estudiante: 0 nulos (0.00%)
estu_fechanacimiento: 0 nulos (0.00%)
estu_genero: 0 nulos (0.00%)
estu_mcpio_presentacion: 0 nulos (0.00%)
estu_mcpio_reside: 0 nulos (0.00%)
estu_nacionalidad: 0 nulos (0.00%)
estu_pais_reside: 0 nulos (0.00%)
estu_privado_libertad: 0 nulos (0.00%)
fami_cuartoshogar: 4330 nulos (2.84%)
fami_educacionmadre: 6088 nulos (3.99%)
fami_educacionpadre: 6108 nulos (4.00%)
fami_estratovivienda: 6514 nulos (4.27%)
fami_personashogar: 4124 nulos (2.70%)
fami_tieneautomovil: 4346 nulos (2.85%)
fami_tienecomputador: 4130 nulos (2.71%)
fami_tieneinternet: 6200 nulos (4.06%)
fami_tienelavadora: 4182 nulos (2.74%)
desemp_ingles: 30 nulos (0.02%)
punt_ingles: 30 nulos (0.02%)
punt_matematicas: 0 nulos (0.00%)
punt_sociales_ciudadanas: 0 nulos (0.00%)
punt_c_naturales: 0 nulos (0.00%)
punt_lectura_critica: 0 nulos (0.00%)
punt_global: 0 nulos (0.00%)

### Duplicidad

In [ ]:
print('Filas duplicadas: ', df.duplicated().sum())
print("Duplicados por estudiante:",df["estu_consecutivo"].duplicated().sum())

Filas duplicadas:  76331
Duplicados por estudiante: 76331

In [ ]:
# ver estudiantes que mas se repiten
df["estu_consecutivo"].value_counts().loc[lambda x: x > 1]

estu_consecutivo
SB11202240072129    4
SB11202240072164    4
SB11202240072126    4
SB11202240071420    4
SB11202240071990    4
                   ..
SB11202240064705    2
SB11202240044533    2
SB11202240262427    2
SB11202240431389    2
SB11202240530614    2
Name: count, Length: 76253, dtype: int64

In [38]:
pd.set_option('display.max_columns', None)

df_duplicados = df[
    df.duplicated(keep=False)
]

display(df_duplicados[df_duplicados['estu_consecutivo']=='SB11202240072129'])

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,cole_cod_mcpio_ubicacion,cole_codigo_icfes,cole_depto_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,cole_nombre_establecimiento,cole_nombre_sede,cole_sede_principal,estu_cod_depto_presentacion,estu_cod_mcpio_presentacion,estu_cod_reside_depto,estu_cod_reside_mcpio,estu_depto_presentacion,estu_depto_reside,estu_estadoinvestigacion,estu_estudiante,estu_fechanacimiento,estu_genero,estu_mcpio_presentacion,estu_mcpio_reside,estu_nacionalidad,estu_pais_reside,estu_privado_libertad,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
35181,20224,TI,SB11202240072129,URBANO,N,A,ACADÉMICO,111001000612,111001000612,11,11001,023382,BOGOTÁ,FEMENINO,TARDE,BOGOTÁ D.C.,OFICIAL,COLEGIO FEMENINO LORENCITA VILLEGAS DE SANTOS ...,SEDE A,S,11,11001,11,11001,BOGOTÁ,BOGOTÁ,PUBLICAR,ESTUDIANTE,23/08/2004,F,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,COLOMBIA,N,Dos,Educación profesional completa,Secundaria (Bachillerato) incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,A2,64,55,64,66,69,318
35182,20224,TI,SB11202240072129,URBANO,N,A,ACADÉMICO,111001000612,111001000612,11,11001,023382,BOGOTÁ,FEMENINO,TARDE,BOGOTÁ D.C.,OFICIAL,COLEGIO FEMENINO LORENCITA VILLEGAS DE SANTOS ...,SEDE A,S,11,11001,11,11001,BOGOTÁ,BOGOTÁ,PUBLICAR,ESTUDIANTE,23/08/2004,F,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,COLOMBIA,N,Dos,Educación profesional completa,Secundaria (Bachillerato) incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,A2,64,55,64,66,69,318
111187,20224,TI,SB11202240072129,URBANO,N,A,ACADÉMICO,111001000612,111001000612,11,11001,023382,BOGOTÁ,FEMENINO,TARDE,BOGOTÁ D.C.,OFICIAL,COLEGIO FEMENINO LORENCITA VILLEGAS DE SANTOS ...,SEDE A,S,11,11001,11,11001,BOGOTÁ,BOGOTÁ,PUBLICAR,ESTUDIANTE,23/08/2004,F,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,COLOMBIA,N,Dos,Educación profesional completa,Secundaria (Bachillerato) incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,A2,64,55,64,66,69,318
111188,20224,TI,SB11202240072129,URBANO,N,A,ACADÉMICO,111001000612,111001000612,11,11001,023382,BOGOTÁ,FEMENINO,TARDE,BOGOTÁ D.C.,OFICIAL,COLEGIO FEMENINO LORENCITA VILLEGAS DE SANTOS ...,SEDE A,S,11,11001,11,11001,BOGOTÁ,BOGOTÁ,PUBLICAR,ESTUDIANTE,23/08/2004,F,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,COLOMBIA,N,Dos,Educación profesional completa,Secundaria (Bachillerato) incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,A2,64,55,64,66,69,318

Se confirma que la duplicidad es en todos los campos

### Tipos de Datos

In [40]:
for columna in df.columns:
    print(f"{columna}: {df[columna].dtype}")

periodo: object
estu_tipodocumento: object
estu_consecutivo: object
cole_area_ubicacion: object
cole_bilingue: object
cole_calendario: object
cole_caracter: object
cole_cod_dane_establecimiento: object
cole_cod_dane_sede: object
cole_cod_depto_ubicacion: object
cole_cod_mcpio_ubicacion: object
cole_codigo_icfes: object
cole_depto_ubicacion: object
cole_genero: object
cole_jornada: object
cole_mcpio_ubicacion: object
cole_naturaleza: object
cole_nombre_establecimiento: object
cole_nombre_sede: object
cole_sede_principal: object
estu_cod_depto_presentacion: object
estu_cod_mcpio_presentacion: object
estu_cod_reside_depto: object
estu_cod_reside_mcpio: object
estu_depto_presentacion: object
estu_depto_reside: object
estu_estadoinvestigacion: object
estu_estudiante: object
estu_fechanacimiento: object
estu_genero: object
estu_mcpio_presentacion: object
estu_mcpio_reside: object
estu_nacionalidad: object
estu_pais_reside: object
estu_privado_libertad: object
fami_cuartoshogar: object
fami_educacionmadre: object
fami_educacionpadre: object
fami_estratovivienda: object
fami_personashogar: object
fami_tieneautomovil: object
fami_tienecomputador: object
fami_tieneinternet: object
fami_tienelavadora: object
desemp_ingles: object
punt_ingles: object
punt_matematicas: object
punt_sociales_ciudadanas: object
punt_c_naturales: object
punt_lectura_critica: object
punt_global: object

Todas las columnas aparecen como object. Esto puede ocurrir porque los datos se descargaron desde Socrata como texto.

### Categorias unicas x cvariable

In [41]:
for col in df.columns:
    print(f'Columna: {col} , Valores Unicos: {df[col].unique()}')

Columna: periodo , Valores Unicos: ['20224']
Columna: estu_tipodocumento , Valores Unicos: ['TI' 'CC' 'NES' 'PEP' 'CR' 'CE' 'PE' 'PPT' 'PC' 'NUIP' 'RC']
Columna: estu_consecutivo , Valores Unicos: ['SB11202240162649' 'SB11202240538873' 'SB11202240109844' ...
 'SB11202240336946' 'SB11202240341473' 'SB11202240399727']
Columna: cole_area_ubicacion , Valores Unicos: ['URBANO' 'RURAL']
Columna: cole_bilingue , Valores Unicos: ['N' 'S' nan]
Columna: cole_calendario , Valores Unicos: ['A' 'OTRO' 'B']
Columna: cole_caracter , Valores Unicos: ['ACADÉMICO' 'TÉCNICO/ACADÉMICO' 'TÉCNICO' nan 'NO APLICA']
Columna: cole_cod_dane_establecimiento , Valores Unicos: ['311848002271' '111850001428' '111001013129' ... '311001065039'
 '311001089981' '311001040168']
Columna: cole_cod_dane_sede , Valores Unicos: ['311848002271' '111850001428' '111001013129' ... '211769003151'
 '311001089981' '311001040168']
Columna: cole_cod_depto_ubicacion , Valores Unicos: ['11']
Columna: cole_cod_mcpio_ubicacion , Valores Unicos: ['11001']
Columna: cole_codigo_icfes , Valores Unicos: ['032730' '658286' '090787' ... '164483' '118331' '079731']
Columna: cole_depto_ubicacion , Valores Unicos: ['BOGOTÁ']
Columna: cole_genero , Valores Unicos: ['MIXTO' 'FEMENINO' 'MASCULINO']
Columna: cole_jornada , Valores Unicos: ['COMPLETA' 'SABATINA' 'TARDE' 'MAÑANA' 'NOCHE' 'UNICA']
Columna: cole_mcpio_ubicacion , Valores Unicos: ['BOGOTÁ D.C.']
Columna: cole_naturaleza , Valores Unicos: ['NO OFICIAL' 'OFICIAL']
Columna: cole_nombre_establecimiento , Valores Unicos: ['COLEGIO DE LA SALLE' 'COLEGIO ALMIRANTE PADILLA (IED)'
 'COLEGIO CLASS (IED)' ... 'COLEGIO COLOMBO JAPONES'
 'INST GUSTAVO ADOLFO BECQUER' 'LICEO SENDERO DEL SABER']
Columna: cole_nombre_sede , Valores Unicos: ['COL DE LA SALLE' 'CENT EDUC DIST ALMIRANTE PADILLA'
 'CENT EDUC DIST CLASS' ... 'CHORRILLOS' 'INST GUSTAVO ADOLFO BECQUER'
 'LICEO SENDERO DEL SABER']
Columna: cole_sede_principal , Valores Unicos: ['S' 'N']
Columna: estu_cod_depto_presentacion , Valores Unicos: ['11' '81' '08' '25' '68' '76' '17' '15' '44' '73' '05' '47' '88' '18'
 '13' '54' '41' '50' '66' '95' '70' '27' '63' '85' '19' '86' '23' '52'
 '20' '91' '99']
Columna: estu_cod_mcpio_presentacion , Valores Unicos: ['11001' '81001' '08001' '25754' '68755' '25126' '76001' '25269' '17001'
 '25035' '15599' '25286' '44847' '25473' '25290' '25740' '25402' '73001'
 '05376' '05579' '17013' '25175' '25183' '25875' '25899' '25151' '76364'
 '25245' '47001' '05308' '05615' '25430' '68077' '25377' '05042' '05360'
 '05212' '15469' '88564' '81794' '18001' '68081' '13001' '54001' '41001'
 '50001' '66001' '54405' '95001' '66440' '41298' '15861' '25307' '41396'
 '05380' '05001' '76520' '70215' '27001' '63001' '05266' '25843' '68001'
 '05736' '25297' '68190' '54720' '15238' '17380' '85001' '19698' '86001'
 '05088' '41359' '25320' '19001' '76892' '05148' '85139' '15693' '15001'
 '25513' '13667' '25815' '73449' '85250' '25040' '25148' '25769' '44430'
 '68307' '23001' '15531' '05318' '15837' '50573' '05440' '73411' '66400'
 '66170' '23466' '88001' '63130' '25386' '73555' '08634' '41551' '54518'
 '76130' '15759' '44650' '25394' '18247' '08638' '70708' '73236' '52001'
 '20001' '68276' '91001' '08758' '15299' '86320' '52683' '17614' '50606'
 '68689' '99001' '47318' '19743' '54498' '15667' '73268' '13052' '08433'
 '17174' '05847' '15516' '05031' '68547' '68444' '73352' '86568' '05631'
 '73408' '15176' '13670' '19418' '73148' '41524' '73168' '05887' '73349'
 '47245' '68615' '17042' '15572' '15757' '18150' '17541' '05761' '73585'
 '50006' '25279' '41306' '50568' '66088' '52399' '68235' '05310' '05664']
Columna: estu_cod_reside_depto , Valores Unicos: ['11' '81' '25' '08' '68' '76' '17' '15' '44' '73' '05' '47' '88' '18'
 '13' '41' '50' '66' '54' '70' '27' '63' '97' '85' '19' '52' '23' '20'
 '86' '99']
Columna: estu_cod_reside_mcpio , Valores Unicos: ['11001' '81001' '25758' '08001' '25754' '68522' '25473' '25126' '76001'
 '25269' '17873' '25035' '25099' '15367' '25286' '44847' '73148' '25290'
 '17001' '25402' '73001' '05376' '05579' '17013' '25175' '25873' '25875'
 '25899' '25178' '76364' '17495' '25214' '25245' '47001' '05308' '05197'
 '25430' '68077' '25377' '05042' '05360' '05212' '15816' '88564' '18001'
 '25785' '68081' '13001' '25658' '41078' '50001' '66001' '54405' '66440'
 '41298' '25322' '15861' '25307' '41396' '41001' '05001' '76520' '70230'
 '25295' '27001' '63001' '05266' '25843' '68001' '97001' '05736' '25297'
 '68190' '54720' '15238' '17380' '85001' '25260' '19698' '05088' '73055'
 '52258' '25183' '25740' '25320' '19001' '76892' '05148' '85139' '15693'
 '25426' '25799' '15001' '25513' '25151' '25200' '25815' '25506' '54001'
 '05615' '73449' '25817' '85250' '25148' '25769' '44430' '23001' '41791'
 '68377' '15531' '05318' '41206' '50573' '05697' '25736' '73411' '66400'
 '66170' '23466' '52835' '63130' '73555' '08634' '54518' '76130' '25486'
 '15759' '25599' '15362' '25530' '18247' '08638' '68689' '70708' '52001'
 '20001' '68276' '08758' '15299' '86320' '25772' '50124' '50606' '99001'
 '47318' '15667' '73770' '08433' '25662' '17174' '25372' '05440' '15500'
 '52480' '05847' '15516' '05031' '68547' '88001' '25181' '25040' '20013'
 '25001' '73226' '86568' '05631' '25645' '15761' '15763' '41006' '25743'
 '25612' '05380' '15176' '19418' '73873' '05282' '41357' '15104' '05887'
 '73349' '17042' '15572' '15757' '25898' '05607' '54498' '17433' '25120'
 '05400' '73408' '05761' '73563' '50006' '25841' '25279' '73275' '25168'
 '73268' '41306' '50568' '66456' '52399' '85430' '05315' '05664']
Columna: estu_depto_presentacion , Valores Unicos: ['BOGOTÁ' 'ARAUCA' 'ATLANTICO' 'CUNDINAMARCA' 'SANTANDER' 'VALLE' 'CALDAS'
 'BOYACA' 'LA GUAJIRA' 'TOLIMA' 'ANTIOQUIA' 'MAGDALENA' 'SAN ANDRES'
 'CAQUETA' 'BOLIVAR' 'NORTE SANTANDER' 'HUILA' 'META' 'RISARALDA'
 'GUAVIARE' 'SUCRE' 'CHOCO' 'QUINDIO' 'CASANARE' 'CAUCA' 'PUTUMAYO'
 'CORDOBA' 'NARIÑO' 'CESAR' 'AMAZONAS' 'VICHADA']
Columna: estu_depto_reside , Valores Unicos: ['BOGOTÁ' 'ARAUCA' 'CUNDINAMARCA' 'ATLANTICO' 'SANTANDER' 'VALLE' 'CALDAS'
 'BOYACA' 'LA GUAJIRA' 'TOLIMA' 'ANTIOQUIA' 'MAGDALENA' 'SAN ANDRES'
 'CAQUETA' 'BOLIVAR' 'HUILA' 'META' 'RISARALDA' 'NORTE SANTANDER' 'SUCRE'
 'CHOCO' 'QUINDIO' 'VAUPES' 'CASANARE' 'CAUCA' 'NARIÑO' 'CORDOBA' 'CESAR'
 'PUTUMAYO' 'VICHADA']
Columna: estu_estadoinvestigacion , Valores Unicos: ['PUBLICAR' 'VALIDEZ OFICINA JURÍDICA']
Columna: estu_estudiante , Valores Unicos: ['ESTUDIANTE']
Columna: estu_fechanacimiento , Valores Unicos: ['14/10/2005' '28/03/1969' '29/11/2003' ... '23/07/1984' '09/12/1994'
 '12/05/2007']
Columna: estu_genero , Valores Unicos: ['M' 'F']
Columna: estu_mcpio_presentacion , Valores Unicos: ['BOGOTÁ D.C.' 'ARAUCA' 'BARRANQUILLA' 'SOACHA' 'SOCORRO' 'CAJICÁ' 'CALI'
 'FACATATIVÁ' 'MANIZALES' 'ANAPOIMA' 'RAMIRIQUÍ' 'FUNZA' 'URIBIA'
 'MOSQUERA' 'FUSAGASUGÁ' 'SIBATÉ' 'LA VEGA' 'IBAGUÉ' 'LA CEJA'
 'PUERTO BERRÍO' 'AGUADAS' 'CHÍA' 'CHOCONTÁ' 'VILLETA' 'ZIPAQUIRÁ'
 'CÁQUEZA' 'JAMUNDÍ' 'EL COLEGIO' 'SANTA MARTA' 'GIRARDOTA' 'RIONEGRO'
 'MADRID' 'BARBOSA' 'LA CALERA' 'SANTA FÉ DE ANTIOQUIA' 'ITAGÜÍ'
 'COPACABANA' 'MONIQUIRÁ' 'PROVIDENCIA' 'TAME' 'FLORENCIA'
 'BARRANCABERMEJA' 'CARTAGENA DE INDIAS' 'CÚCUTA' 'NEIVA' 'VILLAVICENCIO'
 'PEREIRA' 'LOS PATIOS' 'SAN JOSÉ DEL GUAVIARE' 'MARSELLA' 'GARZÓN'
 'VENTAQUEMADA' 'GIRARDOT' 'LA PLATA' 'LA ESTRELLA' 'MEDELLÍN' 'PALMIRA'
 'COROZAL' 'QUIBDÓ' 'ARMENIA' 'ENVIGADO' 'VILLA DE SAN DIEGO DE UBATÉ'
 'BUCARAMANGA' 'SEGOVIA' 'GACHETÁ' 'CIMITARRA' 'SARDINATA' 'DUITAMA'
 'LA DORADA' 'YOPAL' 'SANTANDER DE QUILICHAO' 'MOCOA' 'BELLO' 'ISNOS'
 'GUADUAS' 'POPAYÁN' 'YUMBO' 'EL CARMEN DE VIBORAL' 'MANÍ'
 'SANTA ROSA DE VITERBO' 'TUNJA' 'PACHO' 'SAN MARTÍN DE LOBA' 'TOCAIMA'
 'MELGAR' 'PAZ DE ARIPORO' 'ANOLAIMA' 'CAPARRAPÍ' 'SUBACHOQUE' 'MAICAO'
 'GIRÓN' 'MONTERÍA' 'PAUNA' 'GUARNE' 'TUTA' 'PUERTO LÓPEZ' 'MARINILLA'
 'LÍBANO' 'LA VIRGINIA' 'DOSQUEBRADAS' 'MONTELÍBANO' 'SAN ANDRÉS'
 'CALARCÁ' 'LA MESA' 'PLANADAS' 'SABANAGRANDE' 'PITALITO' 'PAMPLONA'
 'CANDELARIA' 'SOGAMOSO' 'SAN JUAN DEL CESAR' 'LA PALMA' 'EL DONCELLO'
 'SABANALARGA' 'SAN MARCOS' 'DOLORES' 'PASTO' 'VALLEDUPAR' 'FLORIDABLANCA'
 'LETICIA' 'SOLEDAD' 'GARAGOA' 'ORITO' 'SANDONÁ' 'RIOSUCIO' 'RESTREPO'
 'SAN VICENTE DE CHUCURÍ' 'PUERTO CARREÑO' 'GUAMAL' 'SILVIA' 'OCAÑA'
 'SAN LUIS DE GACENO' 'ESPINAL' 'ARJONA' 'MALAMBO' 'CHINCHINÁ' 'URRAO'
 'PAIPA' 'AMALFI' 'PIEDECUESTA' 'MATANZA' 'ICONONZO' 'PUERTO ASÍS'
 'SABANETA' 'LÉRIDA' 'CHIQUINQUIRÁ' 'SAN PABLO' 'LÓPEZ DE MICAY'
 'CARMEN DE APICALÁ' 'PALERMO' 'CHAPARRAL' 'YARUMAL' 'HONDA' 'EL BANCO'
 'ANSERMA' 'PUERTO BOYACÁ' 'SOCHA' 'CARTAGENA DEL CHAIRÁ' 'PENSILVANIA'
 'SOPETRÁN' 'PURIFICACIÓN' 'ACACÍAS' 'FÓMEQUE' 'GIGANTE' 'PUERTO GAITÁN'
 'BELÉN DE UMBRÍA' 'LA UNIÓN' 'EL CARMEN DE CHUCURÍ' 'GÓMEZ PLATA'
 'SAN PEDRO DE LOS MILAGROS']
Columna: estu_mcpio_reside , Valores Unicos: ['BOGOTÁ D.C.' 'ARAUCA' 'SOPÓ' 'BARRANQUILLA' 'SOACHA' 'PALMAR' 'MOSQUERA'
 'CAJICÁ' 'CALI' 'FACATATIVÁ' 'VILLAMARÍA' 'ANAPOIMA' 'BOJACÁ' 'JENESANO'
 'FUNZA' 'URIBIA' 'CARMEN DE APICALÁ' 'FUSAGASUGÁ' 'MANIZALES' 'LA VEGA'
 'IBAGUÉ' 'LA CEJA' 'PUERTO BERRÍO' 'AGUADAS' 'CHÍA' 'VILLAPINZÓN'
 'VILLETA' 'ZIPAQUIRÁ' 'CHIPAQUE' 'JAMUNDÍ' 'NORCASIA' 'COTA' 'EL COLEGIO'
 'SANTA MARTA' 'GIRARDOTA' 'COCORNÁ' 'MADRID' 'BARBOSA' 'LA CALERA'
 'SANTA FÉ DE ANTIOQUIA' 'ITAGÜÍ' 'COPACABANA' 'TOGÜÍ' 'PROVIDENCIA'
 'FLORENCIA' 'TABIO' 'BARRANCABERMEJA' 'CARTAGENA DE INDIAS'
 'SAN FRANCISCO' 'BARAYA' 'VILLAVICENCIO' 'PEREIRA' 'LOS PATIOS'
 'MARSELLA' 'GARZÓN' 'GUASCA' 'VENTAQUEMADA' 'GIRARDOT' 'LA PLATA' 'NEIVA'
 'MEDELLÍN' 'PALMIRA' 'CHALÁN' 'GACHANCIPÁ' 'QUIBDÓ' 'ARMENIA' 'ENVIGADO'
 'VILLA DE SAN DIEGO DE UBATÉ' 'BUCARAMANGA' 'MITÚ' 'SEGOVIA' 'GACHETÁ'
 'CIMITARRA' 'SARDINATA' 'DUITAMA' 'LA DORADA' 'YOPAL' 'EL ROSAL'
 'SANTANDER DE QUILICHAO' 'BELLO' 'ARMERO' 'EL TABLÓN DE GÓMEZ' 'CHOCONTÁ'
 'SIBATÉ' 'GUADUAS' 'POPAYÁN' 'YUMBO' 'EL CARMEN DE VIBORAL' 'MANÍ'
 'SANTA ROSA DE VITERBO' 'MACHETÁ' 'TENJO' 'TUNJA' 'PACHO' 'CÁQUEZA'
 'COGUA' 'TOCAIMA' 'VENECIA' 'CÚCUTA' 'RIONEGRO' 'MELGAR' 'TOCANCIPÁ'
 'PAZ DE ARIPORO' 'CAPARRAPÍ' 'SUBACHOQUE' 'MAICAO' 'MONTERÍA' 'TARQUI'
 'LA BELLEZA' 'PAUNA' 'GUARNE' 'COLOMBIA' 'PUERTO LÓPEZ' 'EL SANTUARIO'
 'SESQUILÉ' 'LÍBANO' 'LA VIRGINIA' 'DOSQUEBRADAS' 'MONTELÍBANO'
 'SAN ANDRÉS DE TUMACO' 'CALARCÁ' 'PLANADAS' 'SABANAGRANDE' 'PAMPLONA'
 'CANDELARIA' 'NEMOCÓN' 'SOGAMOSO' 'APULO' 'IZA' 'PARATEBUENO'
 'EL DONCELLO' 'SABANALARGA' 'SAN VICENTE DE CHUCURÍ' 'SAN MARCOS' 'PASTO'
 'VALLEDUPAR' 'FLORIDABLANCA' 'SOLEDAD' 'GARAGOA' 'ORITO' 'SUESCA'
 'CABUYARO' 'RESTREPO' 'PUERTO CARREÑO' 'GUAMAL' 'SAN LUIS DE GACENO'
 'SUÁREZ' 'MALAMBO' 'SAN JUAN DE RIOSECO' 'CHINCHINÁ' 'JUNÍN' 'MARINILLA'
 'OICATÁ' 'NARIÑO' 'URRAO' 'PAIPA' 'AMALFI' 'PIEDECUESTA' 'SAN ANDRÉS'
 'CHOACHÍ' 'ANOLAIMA' 'AGUSTÍN CODAZZI' 'AGUA DE DIOS' 'CUNDAY'
 'PUERTO ASÍS' 'SABANETA' 'SAN ANTONIO DEL TEQUENDAMA' 'SOMONDOCO'
 'SOTAQUIRÁ' 'ACEVEDO' 'SILVANIA' 'RICAURTE' 'LA ESTRELLA' 'CHIQUINQUIRÁ'
 'LÓPEZ DE MICAY' 'VILLARRICA' 'FREDONIA' 'ÍQUIRA' 'BOYACÁ' 'YARUMAL'
 'HONDA' 'ANSERMA' 'PUERTO BOYACÁ' 'SOCHA' 'ZIPACÓN' 'RETIRO' 'OCAÑA'
 'MANZANARES' 'CABRERA' 'LA UNIÓN' 'LÉRIDA' 'SOPETRÁN' 'PRADO' 'ACACÍAS'
 'UBAQUE' 'FÓMEQUE' 'FLANDES' 'CHAGUANÍ' 'ESPINAL' 'GIGANTE'
 'PUERTO GAITÁN' 'MISTRATÓ' 'TRINIDAD' 'GUADALUPE'
 'SAN PEDRO DE LOS MILAGROS']
Columna: estu_nacionalidad , Valores Unicos: ['COLOMBIA' 'VENEZUELA' 'ECUADOR' 'REPÚBLICA DOMINICANA' 'CABO VERDE'
 'VANUATU' 'ESTADOS UNIDOS' 'CHILE' 'ITALIA' 'PANAMÁ' 'ALEMANIA' 'ESPAÑA'
 'COSTA RICA' 'BRASIL' 'EL SALVADOR' 'PERÚ' 'ARGENTINA' 'PORTUGAL'
 'TURQUÍA' 'GUATEMALA' 'MÉXICO' 'COREA DEL SUR' 'CUBA' 'URUGUAY']
Columna: estu_pais_reside , Valores Unicos: ['COLOMBIA' 'VENEZUELA' 'ECUADOR' 'REPÚBLICA DOMINICANA' 'CABO VERDE'
 'VANUATU' 'ESTADOS UNIDOS' 'CHILE' 'ITALIA' 'PANAMÁ' 'ALEMANIA' 'ESPAÑA'
 'COSTA RICA' 'BRASIL' 'EL SALVADOR' 'PERÚ' 'ARGENTINA' 'PORTUGAL'
 'TURQUÍA' 'GUATEMALA' 'MÉXICO' 'COREA DEL SUR' 'CUBA' 'URUGUAY']
Columna: estu_privado_libertad , Valores Unicos: ['N' 'S']
Columna: fami_cuartoshogar , Valores Unicos: ['Dos' 'Tres' 'Uno' nan 'Cuatro' 'Seis o mas' 'Cinco']
Columna: fami_educacionmadre , Valores Unicos: ['Postgrado' nan 'Primaria incompleta' 'No sabe'
 'Secundaria (Bachillerato) completa' 'Educación profesional incompleta'
 'Primaria completa' 'Técnica o tecnológica incompleta'
 'Técnica o tecnológica completa' 'Ninguno'
 'Educación profesional completa' 'Secundaria (Bachillerato) incompleta'
 'No Aplica']
Columna: fami_educacionpadre , Valores Unicos: ['Postgrado' nan 'Ninguno' 'No sabe' 'No Aplica'
 'Educación profesional completa' 'Primaria incompleta'
 'Secundaria (Bachillerato) incompleta' 'Primaria completa'
 'Secundaria (Bachillerato) completa' 'Técnica o tecnológica completa'
 'Técnica o tecnológica incompleta' 'Educación profesional incompleta']
Columna: fami_estratovivienda , Valores Unicos: ['Estrato 3' nan 'Estrato 2' 'Estrato 4' 'Sin Estrato' 'Estrato 5'
 'Estrato 1' 'Estrato 6']
Columna: fami_personashogar , Valores Unicos: ['3 a 4' '9 o más' nan '5 a 6' '1 a 2' '7 a 8']
Columna: fami_tieneautomovil , Valores Unicos: ['Si' 'No' nan]
Columna: fami_tienecomputador , Valores Unicos: ['Si' 'No' nan]
Columna: fami_tieneinternet , Valores Unicos: ['Si' nan 'No']
Columna: fami_tienelavadora , Valores Unicos: ['Si' 'No' nan]
Columna: desemp_ingles , Valores Unicos: ['B+' 'A-' 'A1' 'A2' 'B1' nan]
Columna: punt_ingles , Valores Unicos: ['80' '32' '48' '59' '47' '46' '100' '38' '58' '70' '35' '78' '44' '75'
 '76' '40' '83' '49' '52' '57' '41' '74' '84' '55' '54' '34' '62' '36'
 '42' '77' '39' '56' '51' '53' '45' '72' '63' '65' '66' '73' '85' '81'
 '30' '79' '69' '60' '37' '43' '67' '50' '33' '71' '61' '68' '31' '64'
 '82' '29' '0' nan '28']
Columna: punt_matematicas , Valores Unicos: ['80' '39' '45' '71' '58' '55' '63' '30' '61' '60' '62' '74' '41' '53'
 '28' '64' '72' '54' '37' '65' '50' '32' '33' '100' '31' '49' '51' '44'
 '48' '47' '46' '42' '52' '76' '22' '69' '43' '57' '68' '73' '59' '20'
 '36' '56' '70' '29' '35' '66' '38' '81' '40' '78' '77' '67' '27' '82'
 '25' '79' '26' '23' '83' '34' '75' '19' '24' '21' '0' '17' '18' '16' '84'
 '15']
Columna: punt_sociales_ciudadanas , Valores Unicos: ['83' '45' '32' '62' '44' '41' '48' '69' '64' '40' '61' '72' '53' '54'
 '63' '60' '36' '43' '51' '70' '35' '55' '34' '79' '38' '59' '47' '56'
 '52' '57' '74' '58' '66' '50' '26' '65' '46' '68' '37' '73' '30' '29'
 '80' '33' '71' '67' '39' '49' '75' '42' '78' '77' '28' '27' '31' '76'
 '25' '22' '23' '24' '81' '85' '100' '0' '19' '21' '82' '20' '84' '86'
 '18']
Columna: punt_c_naturales , Valores Unicos: ['71' '39' '35' '68' '46' '58' '42' '45' '65' '59' '63' '55' '54' '36'
 '66' '62' '47' '37' '61' '72' '44' '67' '56' '74' '32' '79' '57' '52'
 '48' '43' '60' '64' '40' '49' '51' '30' '34' '41' '29' '53' '69' '50'
 '75' '33' '38' '70' '73' '76' '77' '31' '28' '80' '78' '27' '100' '0'
 '26' '25' '81' '82' '24']
Columna: punt_lectura_critica , Valores Unicos: ['78' '44' '47' '79' '60' '65' '67' '46' '52' '42' '68' '43' '59' '73'
 '34' '66' '64' '62' '50' '53' '39' '41' '69' '37' '63' '58' '40' '77'
 '55' '54' '61' '56' '71' '48' '49' '74' '51' '57' '38' '45' '35' '70'
 '36' '72' '76' '31' '30' '32' '27' '75' '29' '33' '100' '80' '26' '81'
 '0' '25' '28' '24' '83' '82']
Columna: punt_global , Valores Unicos: ['391' '205' '202' '346' '236' '298' '348' '208' '253' '335' '192' '328'
 '211' '340' '325' '275' '180' '332' '320' '194' '297' '329' '254' '207'
 '361' '218' '352' '173' '292' '248' '342' '174' '189' '416' '310' '288'
 '268' '265' '220' '259' '239' '237' '291' '267' '227' '256' '295' '222'
 '293' '303' '351' '204' '252' '266' '219' '323' '225' '264' '228' '148'
 '334' '321' '217' '251' '283' '187' '350' '215' '230' '327' '356' '316'
 '287' '163' '339' '277' '250' '231' '319' '193' '200' '245' '257' '272'
 '164' '197' '368' '206' '363' '213' '255' '318' '241' '304' '209' '338'
 '373' '314' '371' '199' '278' '210' '305' '271' '290' '274' '235' '186'
 '285' '243' '260' '195' '333' '378' '375' '284' '360' '317' '365' '315'
 '374' '172' '347' '216' '270' '336' '238' '302' '281' '273' '201' '311'
 '276' '167' '300' '234' '299' '203' '242' '160' '214' '229' '249' '345'
 '326' '183' '393' '337' '324' '282' '353' '383' '344' '196' '247' '312'
 '322' '279' '244' '289' '212' '301' '221' '343' '258' '308' '198' '262'
 '313' '168' '150' '240' '354' '399' '294' '309' '296' '280' '263' '233'
 '330' '223' '379' '185' '306' '357' '176' '372' '384' '307' '232' '178'
 '341' '269' '286' '377' '190' '261' '246' '226' '364' '331' '388' '151'
 '188' '359' '369' '358' '177' '413' '370' '385' '224' '166' '349' '165'
 '367' '355' '170' '182' '171' '181' '191' '158' '169' '366' '162' '404'
 '386' '179' '387' '184' '159' '380' '424' '397' '175' '406' '157' '430'
 '420' '411' '128' '362' '419' '438' '156' '14' '417' '390' '400' '376'
 '381' '161' '382' '427' '153' '152' '396' '389' '394' '423' '149' '402'
 '392' '154' '147' '422' '434' '418' '415' '425' '401' '412' '395' '408'
 '143' '407' '155' '409' '449' '144' '140' '405' '141' '398' '403' '121'
 '108' '118' '410' '414' '116' '437' '145' '421' '146' '135' '446' '428'
 '142' '431' '440' '443' '435' '110' '131' '138' '139' '426' '109' '450'
 '0' '445' '436']

Con esta validacion podemos ir determinando que variables se repiten en informacion o tienen pocos valores, lo que puede hacerla candidata de eliminacion posterior

### Outliers  o valores inesperados

In [45]:
for columna in df.columns:
    if df[columna].dtype == "object":
        print(f"\n{columna}:")
        print(df[columna].value_counts(dropna=False).head(20))

periodo:
periodo
20224    152584
Name: count, dtype: int64

estu_tipodocumento:
estu_tipodocumento
TI      131232
CC       18578
NES        814
CE         718
PEP        564
CR         542
PPT         68
PE          54
NUIP         6
PC           4
RC           4
Name: count, dtype: int64

estu_consecutivo:
estu_consecutivo
SB11202240072129    4
SB11202240072164    4
SB11202240072126    4
SB11202240071420    4
SB11202240071990    4
SB11202240071555    4
SB11202240072155    4
SB11202240072168    4
SB11202240071678    4
SB11202240072145    4
SB11202240072097    4
SB11202240072166    4
SB11202240072137    4
SB11202240072128    4
SB11202240072171    4
SB11202240071898    4
SB11202240072116    4
SB11202240071605    4
SB11202240072084    4
SB11202240072071    4
Name: count, dtype: int64

cole_area_ubicacion:
cole_area_ubicacion
URBANO    151258
RURAL       1326
Name: count, dtype: int64

cole_bilingue:
cole_bilingue
N      123762
NaN     28168
S         654
Name: count, dtype: int64

cole_calendario:
cole_calendario
A       151360
OTRO      1096
B          128
Name: count, dtype: int64

cole_caracter:
cole_caracter
ACADÉMICO            124824
TÉCNICO/ACADÉMICO     16184
NaN                    7036
TÉCNICO                2890
NO APLICA              1650
Name: count, dtype: int64

cole_cod_dane_establecimiento:
cole_cod_dane_establecimiento
111001024732    852
111001030015    794
111001107875    794
111001011819    792
111001010031    748
311001050023    736
111102000753    670
111001104281    654
111001076376    648
111001104329    606
111001106950    586
111001027391    582
111769003360    578
111850001428    574
111001010740    566
111001036781    540
111001002909    540
311001019053    536
111001107816    532
111001106968    530
Name: count, dtype: int64

cole_cod_dane_sede:
cole_cod_dane_sede
111001024732    852
111001030015    794
111001107875    794
111001011819    792
111001010031    748
311001050023    736
111102000753    670
111001104281    654
111001076376    648
111001104329    606
111001106950    586
111001027391    582
111850001428    574
111001010740    566
111001036781    540
111001002909    540
311001019053    536
111001107816    532
111001106968    530
111001083011    520
Name: count, dtype: int64

cole_cod_depto_ubicacion:
cole_cod_depto_ubicacion
11    152584
Name: count, dtype: int64

cole_cod_mcpio_ubicacion:
cole_cod_mcpio_ubicacion
11001    152584
Name: count, dtype: int64

cole_codigo_icfes:
cole_codigo_icfes
740506    736
023366    606
186106    566
019893    536
604769    506
724476    498
717330    490
745620    470
037150    458
720573    452
072934    444
019752    418
102632    408
140095    404
023820    398
088617    398
140103    390
735308    388
053926    376
664953    362
Name: count, dtype: int64

cole_depto_ubicacion:
cole_depto_ubicacion
BOGOTÁ    152584
Name: count, dtype: int64

cole_genero:
cole_genero
MIXTO        144332
FEMENINO       5408
MASCULINO      2844
Name: count, dtype: int64

cole_jornada:
cole_jornada
COMPLETA    47434
MAÑANA      39118
UNICA       30270
TARDE       24360
NOCHE        7212
SABATINA     4190
Name: count, dtype: int64

cole_mcpio_ubicacion:
cole_mcpio_ubicacion
BOGOTÁ D.C.    152584
Name: count, dtype: int64

cole_naturaleza:
cole_naturaleza
OFICIAL       87896
NO OFICIAL    64688
Name: count, dtype: int64

cole_nombre_establecimiento:
cole_nombre_establecimiento
COLEGIO TECNISISTEMAS                                                   1340
COLEGIO INEM FRANCISCO DE PAULA SANTANDER (IED)                          852
COLEGIO CIUDADELA EDUCATIVA DE BOSA (IED)                                794
COLEGIO ENRIQUE OLAYA HERRERA (IED)                                      794
COLEGIO LICEO FEMENINO MERCEDES NARIÑO (IED)                             792
COLEGIO CEDID SAN PABLO (IED)                                            748
COLEGIO DE EDUCACION TECNICA Y ACADEMICA CELESTIN FREINET                736
COLEGIO FERNANDO MAZUERA VILLEGAS (IED)                                  670
COLEGIO GABRIEL BETANCOURT MEJIA (IED)                                   654
COLEGIO MARRUECOS Y MOLINOS (IED)                                        648
COLEGIO CARLOS PIZARRO LEON GOMEZ (IED)                                  606
COLEGIO ALFONSO LOPEZ MICHELSEN (PUERTA DEL SOL) ( IED)                  586
COLEGIO MANUEL CEPEDA VARGAS (IED)                                       582
COLEGIO REPUBLICA DOMINICANA (IED)                                       578
COLEGIO ALMIRANTE PADILLA (IED)                                          574
COLEGIO INSTITUTO TECNICO INDUSTRIAL FRANCISCO JOSE DE CALDAS  (IED)     566
COLEGIO CARLOS ALBAN HOLGUIN (IED)                                       540
COLEGIO RODRIGO LARA BONILLA (IED)                                       540
COLEGIO CAFAM                                                            536
COLEGIO CUNDINAMARCA (IED)                                               532
Name: count, dtype: int64

cole_nombre_sede:
cole_nombre_sede
COLEGIO TECNISISTEMAS - SEDE PRINCIPAL                                                  1010
INEM FRANCISCO DE PAULA SANTANDER                                                        852
COL CUIDADELA EDUCATIVA BOSA (INS EDUC DIST)                                             794
COL DIST ENRIQUE OLAYA HERRERA                                                           794
LICEO FEMENINO MERCEDES NARIÑO                                                           792
CEDID SAN PABLO BOSA                                                                     748
COLEGIO DE EDUCACION TECNICA Y ACADEMICA CELESTIN FREINET - SEDE PRINCIPAL               736
COL DIST FERNANDO MAZUERA VILLEGAS                                                       670
COL GABRIEL BETANCOURT MEJIA (INST EDUC DIST)                                            654
CENT EDUC DIST MARRUECOS Y MOLINOS                                                       648
CARLOS PIZARRO LEON GOMEZ (INST EDUC DIST)                                               606
ALFONSO LÒPEZ MICHELSEN (PUERTA DEL SOL INST EDUC DIST)                                  586
COLEGIO MANUEL CEPEDA VARGAS (IED) - SEDE PRINCIPAL                                      582
CENT EDUC DIST ALMIRANTE PADILLA                                                         574
COLEGIO INSTITUTO TECNICO INDUSTRIAL FRANCISCO JOSE DE CALDAS (IED) - SEDE PRINCIPAL     566
SEDE B                                                                                   562
COL DIST EDUC BAS Y MEDIA RODRIGO LARA BONILLA                                           540
CENT EDUC DIST CARLOS ALBAN HOLGUIN                                                      540
COLEGIO CAFAM                                                                            536
COL CUNDINAMARCA (INS EDUC DIST)                                                         532
Name: count, dtype: int64

cole_sede_principal:
cole_sede_principal
S    147866
N      4718
Name: count, dtype: int64

estu_cod_depto_presentacion:
estu_cod_depto_presentacion
11    149766
25      1624
05       318
73       114
15        86
68        72
76        68
54        66
41        48
18        42
50        42
66        42
08        40
44        36
85        34
17        30
13        28
47        22
27        18
19        16
Name: count, dtype: int64

estu_cod_mcpio_presentacion:
estu_cod_mcpio_presentacion
11001    149766
25754       492
25175       282
25126       126
25430       120
25899        96
05376        94
25269        88
73001        78
25875        64
25286        62
05001        62
25473        58
76001        52
05042        42
25151        38
18001        36
25377        36
54001        32
68001        32
Name: count, dtype: int64

estu_cod_reside_depto:
estu_cod_reside_depto
11    149784
25      1724
05       302
73       100
15        76
68        66
76        60
54        58
41        42
08        42
18        38
66        34
44        34
50        32
85        32
17        26
13        20
47        16
27        16
63        14
Name: count, dtype: int64

estu_cod_reside_mcpio:
estu_cod_reside_mcpio
11001    149784
25754       612
25175       214
25430       116
25126       102
05376        92
25286        64
25269        64
73001        62
25875        62
25899        58
05001        54
25473        54
76001        44
05042        42
25214        42
18001        34
44847        30
68001        30
08001        30
Name: count, dtype: int64

estu_depto_presentacion:
estu_depto_presentacion
BOGOTÁ             149766
CUNDINAMARCA         1624
ANTIOQUIA             318
TOLIMA                114
BOYACA                 86
SANTANDER              72
VALLE                  68
NORTE SANTANDER        66
HUILA                  48
CAQUETA                42
META                   42
RISARALDA              42
ATLANTICO              40
LA GUAJIRA             36
CASANARE               34
CALDAS                 30
BOLIVAR                28
MAGDALENA              22
CHOCO                  18
CAUCA                  16
Name: count, dtype: int64

estu_depto_reside:
estu_depto_reside
BOGOTÁ             149784
CUNDINAMARCA         1724
ANTIOQUIA             302
TOLIMA                100
BOYACA                 76
SANTANDER              66
VALLE                  60
NORTE SANTANDER        58
HUILA                  42
ATLANTICO              42
CAQUETA                38
RISARALDA              34
LA GUAJIRA             34
META                   32
CASANARE               32
CALDAS                 26
BOLIVAR                20
MAGDALENA              16
CHOCO                  16
QUINDIO                14
Name: count, dtype: int64

estu_estadoinvestigacion:
estu_estadoinvestigacion
PUBLICAR                    152536
VALIDEZ OFICINA JURÍDICA        48
Name: count, dtype: int64

estu_estudiante:
estu_estudiante
ESTUDIANTE    152584
Name: count, dtype: int64

estu_fechanacimiento:
estu_fechanacimiento
05/10/2005    318
19/09/2005    316
05/09/2005    314
13/09/2005    304
30/09/2005    294
10/10/2005    294
18/10/2005    290
29/09/2005    288
26/09/2005    288
02/09/2005    288
14/06/2005    286
08/09/2005    286
29/08/2005    286
10/08/2005    284
25/08/2005    284
29/12/2005    284
23/08/2005    282
07/12/2005    280
08/11/2005    280
03/08/2005    280
Name: count, dtype: int64

estu_genero:
estu_genero
F    79844
M    72740
Name: count, dtype: int64

estu_mcpio_presentacion:
estu_mcpio_presentacion
BOGOTÁ D.C.              149766
SOACHA                      492
CHÍA                        282
CAJICÁ                      126
MADRID                      120
ZIPAQUIRÁ                    96
LA CEJA                      94
FACATATIVÁ                   88
IBAGUÉ                       78
VILLETA                      64
FUNZA                        62
MEDELLÍN                     62
MOSQUERA                     58
CALI                         52
SANTA FÉ DE ANTIOQUIA        42
CÁQUEZA                      38
FLORENCIA                    36
LA CALERA                    36
CÚCUTA                       32
BUCARAMANGA                  32
Name: count, dtype: int64

estu_mcpio_reside:
estu_mcpio_reside
BOGOTÁ D.C.              149784
SOACHA                      612
CHÍA                        214
MADRID                      116
CAJICÁ                      102
LA CEJA                      92
FUNZA                        64
FACATATIVÁ                   64
VILLETA                      62
IBAGUÉ                       62
ZIPAQUIRÁ                    58
MEDELLÍN                     54
MOSQUERA                     54
CALI                         44
SANTA FÉ DE ANTIOQUIA        42
COTA                         42
FLORENCIA                    34
BUCARAMANGA                  30
URIBIA                       30
BARRANQUILLA                 30
Name: count, dtype: int64

estu_nacionalidad:
estu_nacionalidad
COLOMBIA                150322
VENEZUELA                 2148
ECUADOR                     30
CHILE                       10
ESTADOS UNIDOS               8
ARGENTINA                    8
BRASIL                       6
GUATEMALA                    6
PERÚ                         4
VANUATU                      4
REPÚBLICA DOMINICANA         4
ITALIA                       4
COSTA RICA                   4
CUBA                         4
EL SALVADOR                  4
CABO VERDE                   2
ALEMANIA                     2
PANAMÁ                       2
ESPAÑA                       2
PORTUGAL                     2
Name: count, dtype: int64

estu_pais_reside:
estu_pais_reside
COLOMBIA                150322
VENEZUELA                 2148
ECUADOR                     30
CHILE                       10
ESTADOS UNIDOS               8
ARGENTINA                    8
BRASIL                       6
GUATEMALA                    6
PERÚ                         4
VANUATU                      4
REPÚBLICA DOMINICANA         4
ITALIA                       4
COSTA RICA                   4
CUBA                         4
EL SALVADOR                  4
CABO VERDE                   2
ALEMANIA                     2
PANAMÁ                       2
ESPAÑA                       2
PORTUGAL                     2
Name: count, dtype: int64

estu_privado_libertad:
estu_privado_libertad
N    152504
S        80
Name: count, dtype: int64

fami_cuartoshogar:
fami_cuartoshogar
Tres          63912
Dos           51326
Cuatro        18428
Cinco          5396
Uno            5170
NaN            4330
Seis o mas     4022
Name: count, dtype: int64

fami_educacionmadre:
fami_educacionmadre
Secundaria (Bachillerato) completa      42430
Educación profesional completa          24520
Secundaria (Bachillerato) incompleta    18402
Técnica o tecnológica completa          17670
Primaria incompleta                      9518
Primaria completa                        8536
Técnica o tecnológica incompleta         7130
Postgrado                                6662
Educación profesional incompleta         6184
NaN                                      6088
No sabe                                  4022
Ninguno                                  1078
No Aplica                                 344
Name: count, dtype: int64

fami_educacionpadre:
fami_educacionpadre
Secundaria (Bachillerato) completa      40308
Secundaria (Bachillerato) incompleta    21626
Educación profesional completa          18130
Primaria incompleta                     13856
No sabe                                 12004
Técnica o tecnológica completa          11406
Primaria completa                        9470
NaN                                      6108
Postgrado                                5162
Técnica o tecnológica incompleta         4992
Educación profesional incompleta         4680
No Aplica                                2826
Ninguno                                  2016
Name: count, dtype: int64

fami_estratovivienda:
fami_estratovivienda
Estrato 2      62920
Estrato 3      52628
Estrato 1      14838
Estrato 4      11412
NaN             6514
Estrato 5       2326
Sin Estrato     1112
Estrato 6        834
Name: count, dtype: int64

fami_personashogar:
fami_personashogar
3 a 4      83860
5 a 6      38652
1 a 2      14794
7 a 8       7746
NaN         4124
9 o más     3408
Name: count, dtype: int64

fami_tieneautomovil:
fami_tieneautomovil
No     93328
Si     54910
NaN     4346
Name: count, dtype: int64

fami_tienecomputador:
fami_tienecomputador
Si     117884
No      30570
NaN      4130
Name: count, dtype: int64

fami_tieneinternet:
fami_tieneinternet
Si     135816
No      10568
NaN      6200
Name: count, dtype: int64

fami_tienelavadora:
fami_tienelavadora
Si     135272
No      13130
NaN      4182
Name: count, dtype: int64

desemp_ingles:
desemp_ingles
A1     44752
A-     42514
A2     35204
B1     23412
B+      6672
NaN       30
Name: count, dtype: int64

punt_ingles:
punt_ingles
56    4976
55    4926
57    4924
54    4872
58    4808
53    4700
52    4662
59    4352
51    4190
50    4148
61    3840
60    3832
49    3772
48    3582
62    3522
47    3270
63    3244
46    3236
64    3202
45    3186
Name: count, dtype: int64

punt_matematicas:
punt_matematicas
54    5506
56    5490
57    5338
58    5330
60    5316
53    5268
55    5266
59    5188
52    5168
51    4998
61    4896
62    4744
50    4732
63    4542
49    4484
48    4180
64    4028
47    4024
65    3710
46    3624
Name: count, dtype: int64

punt_sociales_ciudadanas:
punt_sociales_ciudadanas
55    4956
56    4852
54    4790
59    4696
57    4684
53    4666
52    4658
58    4618
51    4472
60    4436
49    4432
50    4364
47    4350
61    4304
62    4300
48    4134
46    4060
44    3912
63    3882
45    3858
Name: count, dtype: int64

punt_c_naturales:
punt_c_naturales
51    5696
53    5496
50    5492
49    5454
52    5414
54    5376
56    5312
48    5196
55    5132
47    5122
57    5024
46    4970
58    4944
59    4860
45    4726
60    4470
44    4442
43    4376
61    4136
42    4118
Name: count, dtype: int64

punt_lectura_critica:
punt_lectura_critica
59    6110
60    6106
58    6080
57    5858
56    5804
61    5730
62    5552
55    5508
54    5474
63    5352
64    5330
53    5274
65    5012
52    4992
51    4782
66    4506
50    4476
49    4256
67    4248
48    3936
Name: count, dtype: int64

punt_global:
punt_global
277    1410
273    1352
270    1334
250    1332
275    1328
265    1320
278    1318
287    1312
280    1290
292    1288
267    1280
257    1276
268    1272
262    1272
272    1266
243    1266
282    1256
260    1246
293    1240
288    1240
Name: count, dtype: int64

In [47]:
#validacion de puntajes
columnas_puntajes = [
    "punt_global",
    "punt_matematicas",
    "punt_sociales_ciudadanas",
    "punt_c_naturales",
    "punt_lectura_critica",
    "punt_ingles"
]

for columna in columnas_puntajes:
    puntajes = pd.to_numeric(df[columna], errors="coerce")

    print(f"\n{columna}")
    print("Mínimo:", puntajes.min())
    print("Máximo:", puntajes.max())
    print("Valores negativos:", (puntajes < 0).sum())
    print("Valores no numéricos:", (puntajes.isna() & df[columna].notna()).sum())

punt_global
Mínimo: 0
Máximo: 450
Valores negativos: 0
Valores no numéricos: 0

punt_matematicas
Mínimo: 0
Máximo: 100
Valores negativos: 0
Valores no numéricos: 0

punt_sociales_ciudadanas
Mínimo: 0
Máximo: 100
Valores negativos: 0
Valores no numéricos: 0

punt_c_naturales
Mínimo: 0
Máximo: 100
Valores negativos: 0
Valores no numéricos: 0

punt_lectura_critica
Mínimo: 0
Máximo: 100
Valores negativos: 0
Valores no numéricos: 0

punt_ingles
Mínimo: 0.0
Máximo: 100.0
Valores negativos: 0
Valores no numéricos: 0

Se confirma que variables como fecha de nacimiento es correcta y que los rangos en puntajes es el esperado